<?php 
$prd = $this->uri->segment(3);
$thn = substr($prd, 0, 4);
$bln = substr($prd, 4, 6);
$account_labarugi = '504500000000000';
?>

<style type="text/css">
    
    .spinner-wrapper {
        position        : fixed;
        top             : 0;
        left            : 0;
        right           : 0;
        bottom          : 0;
        background-color: #ff6347;
        z-index         : 999999;
    }
    
    body {
        font-family     : Verdana, Geneva, sans-serif;
    }
    
    table {
        font-family     : Arial, Helvetica, sans-serif;
        font-size       : 12px;
        border-collapse : collapse;
    }

    .tbl_tr {
        border-bottom   :1pt solid black;
    }

    .tbl_tr_top {
        border-bottom   :1pt solid black;
        border-top      :1pt solid black;
    }
    
    .wd_table {
        width           :10%;
    }
    
    .bg_sub_total {
        background      : #989898;
    }
    
    .bg_sub_total_sum{
        background: #e2dede;
    }
    
    .teks_tebal{
        font-weight: bold;
    }
    
</style>

<table width="100%" border="0" align="center" class="font-style">
    <tr>
        <td align="left" style="font-size:14px;font-style: italic;">PT MULIA SAWIT AGRO LESTARI</td>
    </tr>
    <tr>
        <td align="center" style="font-size:16px;font-weight:bold;">BALANCE STATEMENT<br/></td>
    </tr>
    <tr>
        <td align="center">
            <?php     
                echo 'TAHUN '.$thn;
            ?>
        </td>
    </tr>
</table>
<br>

<table width="100%" border="0" align="center" class="font-styles">
    <tr>
        <td align="left" style="font-style: italic;">Generated By System MIPS - GL</td>
    </tr>
    <tr>
        <td align="left" style="font-style: italic;">MIS - MSAL GROUP</td>
    </tr>
</table>

<div style="width: 100%;text-align: right;font-size: 10px" class="font-styles">
    Tanggal : <?php echo date("m/d/Y");?>
    <br>
    Waktu   : <?php date_default_timezone_set("Asia/Bangkok"); echo date("h:i:s a",time());?>
</div>

<span style="font-size:10px;font-weight: bold"><i>Sort By Level <?php echo $level;?></i></span>
<br>
<br>
<table border="1" width="100%" class="font-style">
<tbody>
<td align="center" style="width:10px">COA</td>
<td align="center">Name Of Accounts</td>
<td align="center">&nbsp; <?php echo $thn-1;?></td>
<td align="center">&nbsp; Januari</td>
<td align="center">&nbsp; February</td>
<td align="center">&nbsp; Maret</td>
<td align="center">&nbsp; April</td>
<td align="center">&nbsp; Mei</td>
<td align="center">&nbsp; Juni</td>
<td align="center">&nbsp; Juli</td>
<td align="center">&nbsp; Agustus</td>
<td align="center">&nbsp; September</td>
<td align="center">&nbsp; Oktober</td>
<td align="center">&nbsp; November</td>
<td align="center">&nbsp; Desember</td>
<td align="center">&nbsp; Total</td>
</tr>


<!-- Asset -->
<tr style="background-color:#e5e5e5;">
    <td>&nbsp;</td>
    <td colspan="15" style="font-weight:bold">&nbsp;&nbsp; Asset</td>
</tr>
<?php 
$tot01;
$tot02;
$tot03;
$tot04;
$tot05;
$tot06;
$tot07;
$tot08;
$tot09;
$tot010;
$tot011;
$tot012;
$totyears;
$tota;
foreach ($aset_lancar as $b){
    if($b['level'] == 1){
        $f = 'bold';
    }else{
        $f = '';
    }
?>
    <tr>
        <td align="center" width="10%" style="font-weight:<?php echo $f;?>">&nbsp;<?php echo $b['noac'];?></td>
        <td>
            <div style="padding-left:<?php echo $b['level'];?>0px;font-weight:<?php echo $f;?>"><?php echo $b['nama'];?></div>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['yeard'] <> 0){
                echo number_format($b['yeard'],0);
                $totyears     += $b['yeard'];
            }else{
                $nominalyeard   = $b['yearc']*'-1';
                $totyears     += $nominalyeard;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominalyeard,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo01d'] <> 0){
                $nominal01  = $b['saldo01d'];
                $tot01     += $nominal01;
                echo number_format($nominal01,0);
            }else{
                $nominal01 = $b['saldo01c']*-1;
                $tot01     += $nominal01;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal01,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo02d'] <> 0){
                $nominal02  = $b['saldo02d'];
                $tot02     += $nominal02;
                echo number_format($nominal02,0);
            }else{
                $nominal02 = $b['saldo02c']*-1;
                $tot02     += $nominal02;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal02,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo03d'] <> 0){
                $nominal03  = $b['saldo03d'];
                $tot03     += $nominal03;
                echo number_format($nominal03,0);
            }else{
                $nominal03 = $b['saldo03c']*-1;
                $tot03     += $nominal03;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal03,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo04d'] <> 0){
                $nominal04  = $b['saldo04d'];
                $tot04     += $nominal04;
                echo number_format($nominal04,0);
            }else{
                $nominal04 = $b['saldo04c']*-1;
                $tot04     += $nominal04;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal04,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo05d'] <> 0){
                $nominal05  = $b['saldo05d'];
                $tot05     += $nominal05;
                echo number_format($nominal05,0);
            }else{
                $nominal05 = $b['saldo05c']*-1;
                $tot05     += $nominal05;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal05,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo06d'] <> 0){
                $nominal06  = $b['saldo06d'];
                $tot06     += $nominal06;
                echo number_format($nominal06,0);
            }else{
                $nominal06 = $b['saldo06c']*-1;
                $tot06     += $nominal06;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal06,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo07d'] <> 0){
                $nominal07  = $b['saldo07d'];
                $tot07     += $nominal07;
                echo number_format($nominal07,0);
            }else{
                $nominal07 = $b['saldo07c']*-1;
                $tot07     += $nominal07;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal07,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo08d'] <> 0){
                $nominal08  = $b['saldo08d'];
                $tot08     += $nominal08;
                echo number_format($nominal08,0);
            }else{
                $nominal08 = $b['saldo08c']*-1;
                $tot08     += $nominal08;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal08,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo09d'] <> 0){
                $nominal09  = $b['saldo09d'];
                $tot09     += $nominal09;
                echo number_format($nominal09,0);
            }else{
                $nominal09 = $b['saldo09c']*-1;
                $tot09     += $nominal09;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal09,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo10d'] <> 0){
                $nominal10  = $b['saldo10d'];
                $tot10     += $nominal10;
                echo number_format($nominal10,0);
            }else{
                $nominal10 = $b['saldo10c']*-1;
                $tot10     += $nominal10;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal10,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo11d'] <> 0){
                $nominal11  = $b['saldo11d'];
                $tot11     += $nominal11;
                echo number_format($nominal11,0);
            }else{
                $nominal11 = $b['saldo11c']*-1;
                $tot11     += $nominal11;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal11,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo12d'] <> 0){
                $nominal12  = $b['saldo12d'];
                $tot12     += $nominal12;
                echo number_format($nominal12,0);
            }else{
                $nominal12 = $b['saldo12c']*-1;
                $tot12     += $nominal12;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal12,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
                $tot_row = $nominal01+$nominal02+$nominal03+$nominal04+$nominal05+$nominal06+$nominal07+$nominal08+$nominal09+$nominal10+$nominal11+$nominal12;
                $tota     += $tot_row;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_row,0));
            ?>
        </td>
    </tr>
<?php 
}
?>
<!-- End Aset Lancar -->  


<!--Start Aset Tidak Lancar-->
<?php 
foreach($aset_tidak_lancar as $b){
    
    if($b['level'] == 1){
        $f = 'bold';
    }else{
        $f = '';
    }
    
?>
<tr>
        <td align="center" width="10%" style="font-weight:<?php echo $f;?>">&nbsp;<?php echo $b['noac'];?></td>
        <td>
            <div style="padding-left:<?php echo $b['level'];?>0px;font-weight:<?php echo $f;?>"><?php echo $b['nama'];?></div>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['yeard'] <> 0){
                echo number_format($b['yeard'],0);
                $totyears     += $b['yeard'];
            }else{
                $nominalyeard   = $b['yearc']*'-1';
                $totyears     += $nominalyeard;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominalyeard,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo01d'] <> 0){
                $nominal_atl_01  = $b['saldo01d'];
                $tot01     += $nominal_atl_01;
                echo number_format($nominal_atl_01,0);
            }else{
                $nominal_atl_01 = $b['saldo01c']*-1;
                $tot01     += $nominal_atl_01;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal_atl_01,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo02d'] <> 0){
                $nominal_atl_02  = $b['saldo02d'];
                $tot02     += $nominal_atl_02;
                echo number_format($nominal_atl_02,0);
            }else{
                $nominal_atl_02 = $b['saldo02c']*-1;
                $tot02     += $nominal_atl_02;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal_atl_02,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo03d'] <> 0){
                $nominal_atl_03  = $b['saldo03d'];
                $tot03     += $nominal_atl_03;
                echo number_format($nominal_atl_03,0);
            }else{
                $nominal_atl_03 = $b['saldo03c']*-1;
                $tot03     += $nominal03;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal03,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo04d'] <> 0){
                $nominal_atl_04  = $b['saldo04d'];
                $tot04     += $nominal_atl_04;
                echo number_format($nominal_atl_04,0);
            }else{
                $nominal04 = $b['saldo04c']*-1;
                $tot04     += $nominal_atl_04;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal_atl_04,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo05d'] <> 0){
                $nominal_atl_05  = $b['saldo05d'];
                $tot05     += $nominal_atl_05;
                echo number_format($nominal_atl_05,0);
            }else{
                $nominal_atl_05 = $b['saldo05c']*-1;
                $tot05     += $nominal_atl_05;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal_atl_05,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo06d'] <> 0){
                $nominal_atl_06  = $b['saldo06d'];
                $tot06     += $nominal_atl_06;
                echo number_format($nominal_atl_06,0);
            }else{
                $nominal_atl_06 = $b['saldo06c']*-1;
                $tot06     += $nominal_atl_06;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal_atl_06,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo07d'] <> 0){
                $nominal_atl_07  = $b['saldo07d'];
                $tot07     += $nominal_atl_07;
                echo number_format($nominal_atl_07,0);
            }else{
                $nominal_atl_07 = $b['saldo07c']*-1;
                $tot07     += $nominal_atl_07;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal_atl_07,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo08d'] <> 0){
                $nominal_atl_08  = $b['saldo08d'];
                $tot08     += $nominal_atl_08;
                echo number_format($nominal_atl_08,0);
            }else{
                $nominal_atl_08 = $b['saldo08c']*-1;
                $tot08     += $nominal_atl_08;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal_atl_08,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo09d'] <> 0){
                $nominal_atl_09  = $b['saldo09d'];
                $tot09     += $nominal_atl_09;
                echo number_format($nominal_atl_09,0);
            }else{
                $nominal_atl_09 = $b['saldo09c']*-1;
                $tot09     += $nominal_atl_09;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal_atl_09,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo10d'] <> 0){
                $nominal_atl_10  = $b['saldo10d'];
                $tot10     += $nominal_atl_10;
                echo number_format($nominal_atl_10,0);
            }else{
                $nominal_atl_10 = $b['saldo10c']*-1;
                $tot10     += $nominal_atl_10;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal_atl_10,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo11d'] <> 0){
                $nominal_atl_11  = $b['saldo11d'];
                $tot11     += $nominal_atl_11;
                echo number_format($nominal_atl_11,0);
            }else{
                $nominal_atl_11 = $b['saldo11c']*-1;
                $tot11     += $nominal_atl_11;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal_atl_11,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo12d'] <> 0){
                $nominal_atl_12  = $b['saldo12d'];
                $tot12     += $nominal_atl_12;
                echo number_format($nominal_atl_12,0);
            }else{
                $nominal_atl_12 = $b['saldo12c']*-1;
                $tot12     += $nominal_atl_12;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal_atl_12,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
                $tot_row = $nominal_atl_01+$nominal_atl_02+$nominal_atl_03+$nominal_atl_04+$nominal_atl_05+$nominal_atl_06+$nominal_atl_07+$nominal_atl_08+$nominal_atl_09+$nominal_atl_10+$nominal_atl_11+$nominal_atl_12;
                //$tota     += $tot_row;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_row,0));
            ?>
        </td>
    </tr>
<!--End Aset Tidak Lancar-->
<?php 
}
?>


<tr>
<td colspan="2" align="right" class="bg_sub_total">&nbsp;Sub Total</td>
<td style="text-align: right;" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($totyears,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot01,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot02,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot03,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot04,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot05,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot06,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot07,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot08,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot09,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot10,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot11,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot12,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tota,0));?>
</td>
<!-- Sub Total -->
</tr>
<!-- Asset -->




<!-- Liability -->
<tr style="background-color:#e5e5e5;">
    <td>&nbsp;</td>
    <td colspan="15" style="font-weight:bold">&nbsp;&nbsp; Liability</td>
</tr>
<?php 
$tot_lia_01;
$tot_lia_02;
$tot_lia_03;
$tot_lia_04;
$tot_lia_05;
$tot_lia_06;
$tot_lia_07;
$tot_lia_08;
$tot_lia_09;
$tot_lia_010;
$tot_lia_011;
$tot_lia_012;
$tot_lia_years;
$tot_lia;
foreach ($balance_kewajiban_lancar as $b){
    if($b['level'] == 1){
        $f = 'bold';
    }else{
        $f = '';
    }
?>
    <tr>
        <td align="center" width="10%" style="font-weight:<?php echo $f;?>">&nbsp;<?php echo $b['noac'];?></td>
        <td>
            <div style="padding-left:<?php echo $b['level'];?>0px;font-weight:<?php echo $f;?>"><?php echo $b['nama'];?></div>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['yeard'] <> 0){
                echo number_format($b['yeard'],0);
                $tot_lia_years     += $b['yeard'];
            }else{
                $nominalyeard   = $b['yearc']*'-1';
                $tot_lia_years     += $nominalyeard;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominalyeard,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo01d'] <> 0){
                $nominal01  = $b['saldo01d'];
                $tot_lia_01     += $nominal01;
                echo number_format($nominal01,0);
            }else{
                $nominal01 = $b['saldo01c']*-1;
                $tot_lia_01     += $nominal01;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal01,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo02d'] <> 0){
                $nominal02  = $b['saldo02d'];
                $tot_lia_02     += $nominal02;
                echo number_format($nominal02,0);
            }else{
                $nominal02 = $b['saldo02c']*-1;
                $tot_lia_02     += $nominal02;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal02,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo03d'] <> 0){
                $nominal03  = $b['saldo03d'];
                $tot_lia_03     += $nominal03;
                echo number_format($nominal03,0);
            }else{
                $nominal03 = $b['saldo03c']*-1;
                $tot_lia_03     += $nominal03;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal03,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo04d'] <> 0){
                $nominal04  = $b['saldo04d'];
                $tot_lia_04     += $nominal04;
                echo number_format($nominal04,0);
            }else{
                $nominal04 = $b['saldo04c']*-1;
                $tot_lia_04     += $nominal04;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal04,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo05d'] <> 0){
                $nominal05  = $b['saldo05d'];
                $tot_lia_05     += $nominal05;
                echo number_format($nominal05,0);
            }else{
                $nominal05 = $b['saldo05c']*-1;
                $tot_lia_05     += $nominal05;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal05,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo06d'] <> 0){
                $nominal06  = $b['saldo06d'];
                $tot_lia_06     += $nominal06;
                echo number_format($nominal06,0);
            }else{
                $nominal06 = $b['saldo06c']*-1;
                $tot_lia_06     += $nominal06;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal06,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo07d'] <> 0){
                $nominal07  = $b['saldo07d'];
                $tot_lia_07     += $nominal07;
                echo number_format($nominal07,0);
            }else{
                $nominal07 = $b['saldo07c']*-1;
                $tot_lia_07     += $nominal07;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal07,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo08d'] <> 0){
                $nominal08  = $b['saldo08d'];
                $tot_lia_08     += $nominal08;
                echo number_format($nominal08,0);
            }else{
                $nominal08 = $b['saldo08c']*-1;
                $tot_lia_08     += $nominal08;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal08,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo09d'] <> 0){
                $nominal09  = $b['saldo09d'];
                $tot_lia_09     += $nominal09;
                echo number_format($nominal09,0);
            }else{
                $nominal09 = $b['saldo09c']*-1;
                $tot_lia_09     += $nominal09;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal09,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo10d'] <> 0){
                $nominal10  = $b['saldo10d'];
                $tot_lia_10     += $nominal10;
                echo number_format($nominal10,0);
            }else{
                $nominal10 = $b['saldo10c']*-1;
                $tot_lia_10     += $nominal10;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal10,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo11d'] <> 0){
                $nominal11  = $b['saldo11d'];
                $tot_lia_11     += $nominal11;
                echo number_format($nominal11,0);
            }else{
                $nominal11 = $b['saldo11c']*-1;
                $tot_lia_11     += $nominal11;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal11,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo12d'] <> 0){
                $nominal12  = $b['saldo12d'];
                $tot_lia_12     += $nominal12;
                echo number_format($nominal12,0);
            }else{
                $nominal12 = $b['saldo12c']*-1;
                $tot_lia_12     += $nominal12;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal12,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
                $tot_row = $nominal01+$nominal02+$nominal03+$nominal04+$nominal05+$nominal06+$nominal07+$nominal08+$nominal09+$nominal10+$nominal11+$nominal12;
                $tot_lia     += $tot_row;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_row,0));
            ?>
        </td>
    </tr>
<?php 
}
?>
    
    
<?php 
foreach ($balance_kewajiban_tidak_lancar as $b){
    if($b['level'] == 1){
        $f = 'bold';
    }else{
        $f = '';
    }
?>
    <tr>
        <td align="center" width="10%" style="font-weight:<?php echo $f;?>">&nbsp;<?php echo $b['noac'];?></td>
        <td>
            <div style="padding-left:<?php echo $b['level'];?>0px;font-weight:<?php echo $f;?>"><?php echo $b['nama'];?></div>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['yeard'] <> 0){
                echo number_format($b['yeard'],0);
                $tot_lia_years     += $b['yeard'];
            }else{
                $nominalyeard   = $b['yearc']*'-1';
                $tot_lia_years     += $nominalyeard;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominalyeard,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo01d'] <> 0){
                $nominal01  = $b['saldo01d'];
                $tot_lia_01     += $nominal01;
                echo number_format($nominal01,0);
            }else{
                $nominal01 = $b['saldo01c']*-1;
                $tot_lia_01     += $nominal01;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal01,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo02d'] <> 0){
                $nominal02  = $b['saldo02d'];
                $tot_lia_02     += $nominal02;
                echo number_format($nominal02,0);
            }else{
                $nominal02 = $b['saldo02c']*-1;
                $tot_lia_02     += $nominal02;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal02,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo03d'] <> 0){
                $nominal03  = $b['saldo03d'];
                $tot_lia_03     += $nominal03;
                echo number_format($nominal03,0);
            }else{
                $nominal03 = $b['saldo03c']*-1;
                $tot_lia_03     += $nominal03;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal03,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo04d'] <> 0){
                $nominal04  = $b['saldo04d'];
                $tot_lia_04     += $nominal04;
                echo number_format($nominal04,0);
            }else{
                $nominal04 = $b['saldo04c']*-1;
                $tot_lia_04     += $nominal04;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal04,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo05d'] <> 0){
                $nominal05  = $b['saldo05d'];
                $tot_lia_05     += $nominal05;
                echo number_format($nominal05,0);
            }else{
                $nominal05 = $b['saldo05c']*-1;
                $tot_lia_05     += $nominal05;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal05,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo06d'] <> 0){
                $nominal06  = $b['saldo06d'];
                $tot_lia_06     += $nominal06;
                echo number_format($nominal06,0);
            }else{
                $nominal06 = $b['saldo06c']*-1;
                $tot_lia_06     += $nominal06;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal06,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo07d'] <> 0){
                $nominal07  = $b['saldo07d'];
                $tot_lia_07     += $nominal07;
                echo number_format($nominal07,0);
            }else{
                $nominal07 = $b['saldo07c']*-1;
                $tot_lia_07     += $nominal07;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal07,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo08d'] <> 0){
                $nominal08  = $b['saldo08d'];
                $tot_lia_08     += $nominal08;
                echo number_format($nominal08,0);
            }else{
                $nominal08 = $b['saldo08c']*-1;
                $tot_lia_08     += $nominal08;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal08,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo09d'] <> 0){
                $nominal09  = $b['saldo09d'];
                $tot_lia_09     += $nominal09;
                echo number_format($nominal09,0);
            }else{
                $nominal09 = $b['saldo09c']*-1;
                $tot_lia_09     += $nominal09;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal09,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo10d'] <> 0){
                $nominal10  = $b['saldo10d'];
                $tot_lia_10 += $nominal10;
                echo number_format($nominal10,0);
            }else{
                $nominal10  = $b['saldo10c']*-1;
                $tot_lia_10 += $nominal10;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal10,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo11d'] <> 0){
                $nominal11  = $b['saldo11d'];
                $tot_lia_11     += $nominal11;
                echo number_format($nominal11,0);
            }else{
                $nominal11 = $b['saldo11c']*-1;
                $tot_lia_11     += $nominal11;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal11,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo12d'] <> 0){
                $nominal12  = $b['saldo12d'];
                $tot_lia_12     += $nominal12;
                echo number_format($nominal12,0);
            }else{
                $nominal12 = $b['saldo12c']*-1;
                $tot_lia_12     += $nominal12;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal12,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
                $tot_row = $nominal01+$nominal02+$nominal03+$nominal04+$nominal05+$nominal06+$nominal07+$nominal08+$nominal09+$nominal10+$nominal11+$nominal12;
                $tot_lia     += $tot_row;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_row,0));
            ?>
        </td>
    </tr>
<?php 
}
?>    
    
    
    
    <tr>
<td colspan="2" align="right" class="bg_sub_total">&nbsp;Sub Total</td>
<td style="text-align: right;" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia_years,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia_01,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia_02,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia_03,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia_04,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia_05,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia_06,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia_07,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia_08,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia_09,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia_10,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia_11,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia_12,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia,0));?>
</td>
<!-- Sub Total -->
</tr>
<!-- Liability -->



<!-- Capital -->
<tr style="background-color:#e5e5e5;">
    <td>&nbsp;</td>
    <td colspan="15" style="font-weight:bold">&nbsp;&nbsp; Capital</td>
</tr>
<?php 
$tot_cap_01;
$tot_cap_02;
$tot_cap_03;
$tot_cap_04;
$tot_cap_05;
$tot_cap_06;
$tot_cap_07;
$tot_cap_08;
$tot_cap_09;
$tot_cap_010;
$tot_cap_011;
$tot_cap_012;
$tot_cap_years;
$tot_cap;
foreach ($balance_ekuitas as $b){
    if($b['level'] == 1){
        $f = 'bold';
    }else{
        $f = '';
    }
?>
    <tr>
        <td align="center" width="10%" style="font-weight:<?php echo $f;?>">&nbsp;<?php echo $b['noac'];?></td>
        <td>
            <div style="padding-left:<?php echo $b['level'];?>0px;font-weight:<?php echo $f;?>"><?php echo $b['nama'];?></div>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['yeard'] <> 0){
                echo number_format($b['yeard'],0);
                $tot_cap_years     += $b['yeard'];
            }else{
                $nominalyeard   = $b['yearc']*'-1';
                $tot_cap_years     += $nominalyeard;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominalyeard,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo01d'] <> 0){
                $nominal01  = $b['saldo01d'];
                $tot_cap_01     += $nominal01;
                echo number_format($nominal01,0);
            }else{
                $nominal01 = $b['saldo01c']*-1;
                $tot_cap_01     += $nominal01;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal01,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo02d'] <> 0){
                $nominal02  = $b['saldo02d'];
                $tot_cap_02     += $nominal02;
                echo number_format($nominal02,0);
            }else{
                $nominal02 = $b['saldo02c']*-1;
                $tot_cap_02     += $nominal02;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal02,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo03d'] <> 0){
                $nominal03  = $b['saldo03d'];
                $tot_cap_03     += $nominal03;
                echo number_format($nominal03,0);
            }else{
                $nominal03 = $b['saldo03c']*-1;
                $tot_cap_03     += $nominal03;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal03,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo04d'] <> 0){
                $nominal04  = $b['saldo04d'];
                $tot_cap_04     += $nominal04;
                echo number_format($nominal04,0);
            }else{
                $nominal04 = $b['saldo04c']*-1;
                $tot_cap_04     += $nominal04;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal04,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo05d'] <> 0){
                $nominal05  = $b['saldo05d'];
                $tot_cap_05     += $nominal05;
                echo number_format($nominal05,0);
            }else{
                $nominal05 = $b['saldo05c']*-1;
                $tot_cap_05     += $nominal05;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal05,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo06d'] <> 0){
                $nominal06  = $b['saldo06d'];
                $tot_cap_06 += $nominal06;
                echo number_format($nominal06,0);
            }else{
                $nominal06  = $b['saldo06c']*-1;
                $tot_cap_06 += $nominal06;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal06,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo07d'] <> 0){
                $nominal07  = $b['saldo07d'];
                $tot_cap_07     += $nominal07;
                echo number_format($nominal07,0);
            }else{
                $nominal07 = $b['saldo07c']*-1;
                $tot_cap_07     += $nominal07;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal07,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo08d'] <> 0){
                $nominal08  = $b['saldo08d'];
                $tot_cap_08     += $nominal08;
                echo number_format($nominal08,0);
            }else{
                $nominal08 = $b['saldo08c']*-1;
                $tot_cap_08     += $nominal08;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal08,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo09d'] <> 0){
                $nominal09  = $b['saldo09d'];
                $tot_cap_09     += $nominal09;
                echo number_format($nominal09,0);
            }else{
                $nominal09 = $b['saldo09c']*-1;
                $tot_cap_09     += $nominal09;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal09,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo10d'] <> 0){
                $nominal10  = $b['saldo10d'];
                $tot_cap_10     += $nominal10;
                echo number_format($nominal10,0);
            }else{
                $nominal10 = $b['saldo10c']*-1;
                $tot_cap_10     += $nominal10;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal10,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo11d'] <> 0){
                $nominal11  = $b['saldo11d'];
                $tot_cap_11     += $nominal11;
                echo number_format($nominal11,0);
            }else{
                $nominal11 = $b['saldo11c']*-1;
                $tot_cap_11     += $nominal11;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal11,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
            if($b['saldo12d'] <> 0){
                $nominal12  = $b['saldo12d'];
                $tot_cap_12     += $nominal12;
                echo number_format($nominal12,0);
            }else{
                $nominal12 = $b['saldo12c']*-1;
                $tot_cap_12     += $nominal12;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nominal12,0));
            }
            ?>
        </td>
        <td style="text-align: right;font-weight:<?php echo $f;?>">
            <?php 
                $tot_row = $nominal01+$nominal02+$nominal03+$nominal04+$nominal05+$nominal06+$nominal07+$nominal08+$nominal09+$nominal10+$nominal11+$nominal12;
                $tot_cap     += $tot_row;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_row,0));
            ?>
        </td>
    </tr>
<?php 
}
?>
    
<tr>
<td colspan="2" align="right" class="bg_sub_total">&nbsp;Sub Total</td>
<td style="text-align: right;" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_cap_years,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_cap_01,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_cap_02,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_cap_03,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_cap_04,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_cap_05,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_cap_06,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_cap_07,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_cap_08,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_cap_09,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_cap_10,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_cap_11,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_cap_12,0));?>
</td>
<td style="text-align: right" class="bg_sub_total teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_cap,0));?>
</td>
<!-- Sub Total -->
</tr>
<!-- Capital -->


<!-- Kewajiban + Equitas -->
<tr>
    <td colspan="2" align="right" class="bg_sub_total_sum" style="font-size:14px;font-weight: bold;">&nbsp;KEWAJIBAN + EQUITAS</td>
<td style="text-align: right;" class="bg_sub_total_sum teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia_years+$tot_cap_years,0));?>
</td>
<td style="text-align: right" class="bg_sub_total_sum teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia_01+$tot_cap_01,0));?>
</td>
<td style="text-align: right" class="bg_sub_total_sum teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia_02+$tot_cap_02,0));?>
</td>
<td style="text-align: right" class="bg_sub_total_sum teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia_03+$tot_cap_03,0));?>
</td>
<td style="text-align: right" class="bg_sub_total_sum teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia_04+$tot_cap_04,0));?>
</td>
<td style="text-align: right" class="bg_sub_total_sum teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia_05+$tot_cap_05,0));?>
</td>
<td style="text-align: right" class="bg_sub_total_sum teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia_06+$tot_cap_06,0));?>
</td>
<td style="text-align: right" class="bg_sub_total_sum teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia_07+$tot_cap_07,0));?>
</td>
<td style="text-align: right" class="bg_sub_total_sum teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia_08+$tot_cap_08,0));?>
</td>
<td style="text-align: right" class="bg_sub_total_sum teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia_09+$tot_cap_09,0));?>
</td>
<td style="text-align: right" class="bg_sub_total_sum teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia_10+$tot_cap_10,0));?>
</td>
<td style="text-align: right" class="bg_sub_total_sum teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia_11+$tot_cap_11,0));?>
</td>
<td style="text-align: right" class="bg_sub_total_sum teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia_12+$tot_cap_12,0));?>
</td>
<td style="text-align: right" class="bg_sub_total_sum teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_lia+$tot_cap,0));?>
</td>
<!-- Kewajiban + Equitas -->
</tr>



<!-- Kewajiban + Equitas -->
<?php 
    $sums_year                = $tot_lia_years+$tot_cap_years;
    $sums_kwajiban_equitas_01 = $tot_lia_01+$tot_cap_01;
    $sums_kwajiban_equitas_02 = $tot_lia_02+$tot_cap_02;
    $sums_kwajiban_equitas_03 = $tot_lia_03+$tot_cap_03;
    $sums_kwajiban_equitas_04 = $tot_lia_04+$tot_cap_04;
    $sums_kwajiban_equitas_05 = $tot_lia_05+$tot_cap_05;
    $sums_kwajiban_equitas_06 = $tot_lia_06+$tot_cap_06;
    $sums_kwajiban_equitas_07 = $tot_lia_07+$tot_cap_07;
    $sums_kwajiban_equitas_08 = $tot_lia_08+$tot_cap_08;
    $sums_kwajiban_equitas_09 = $tot_lia_09+$tot_cap_09;
    $sums_kwajiban_equitas_10 = $tot_lia_10+$tot_cap_10;
    $sums_kwajiban_equitas_11 = $tot_lia_11+$tot_cap_11;
    $sums_kwajiban_equitas_12 = $tot_lia_12+$tot_cap_12;
    
?>
<tr>
    <td colspan="2" align="right" class="bg_sub_total_sum" style="font-size:12px;font-weight: bold;">&nbsp;Balance</td>
<td style="text-align: right;font-size:12px;" class="bg_sub_total_sum teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($totyears-$sums_year,0));?>
</td>
<td style="text-align: right;font-size:12px;" class="bg_sub_total_sum teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot01-$sums_kwajiban_equitas_01,0));?>
</td>
<td style="text-align: right;font-size:12px;" class="bg_sub_total_sum teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot02-$sums_kwajiban_equitas_02,0));?>
</td>
<td style="text-align: right;font-size:12px;" class="bg_sub_total_sum teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot03-$sums_kwajiban_equitas_03,0));?>
</td>
<td style="text-align: right;font-size:12px;" class="bg_sub_total_sum teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot04-$sums_kwajiban_equitas_04,0));?>
</td>
<td style="text-align: right;font-size:12px;" class="bg_sub_total_sum teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot05-$sums_kwajiban_equitas_05,0));?>
</td>
<td style="text-align: right;font-size:12px;" class="bg_sub_total_sum teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot06-$sums_kwajiban_equitas_06,0));?>
</td>
<td style="text-align: right;font-size:12px;" class="bg_sub_total_sum teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot07-$sums_kwajiban_equitas_07,0));?>
</td>
<td style="text-align: right;font-size:12px;" class="bg_sub_total_sum teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot08-$sums_kwajiban_equitas_08,0));?>
</td>
<td style="text-align: right;font-size:12px;" class="bg_sub_total_sum teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot09-$sums_kwajiban_equitas_09,0));?>
</td>
<td style="text-align: right;font-size:12px;" class="bg_sub_total_sum teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot10-$sums_kwajiban_equitas_10,0));?>
</td>
<td style="text-align: right;font-size:12px;" class="bg_sub_total_sum teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot11-$sums_kwajiban_equitas_11,0));?>
</td>
<td style="text-align: right;font-size:12px;" class="bg_sub_total_sum teks_tebal">&nbsp;
    <?php echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot12-$sums_kwajiban_equitas_12,0));?>
</td>
<!-- Kewajiban + Equitas -->
</tr>




</tbody>
</table>



<br>
<br>


                     