<?php

$prd = $this->uri->segment(3);
$thn = substr($prd, 0, 4);
$bln = substr($prd, 4, 6);
$account_labarugi = '504500000000000';
?>
<!-- START : KONDISI 
if {noac.group}="Revenue"then  "PENDAPATAN"
else if {noac.group}="Expenses" THEN
    (IF Left ({noac.noac}, 2)="70" THEN "HARGA POKOK PENJUALAN")
else if {noac.group}="Other Expenses" then "BIAYA LAINNYA"
else if {noac.group}="Other Revenue" then "PENDAPATAN LAINNYA"
    END : KONDISI -->
<style>
    .spinner-wrapper {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: #ff6347;
        z-index: 999999;
    }

    body {
        font-family: Verdana, Geneva, sans-serif;
    }

    table {
        font-family: Verdana, Geneva, sans-serif;
        font-size: 10px;
        border-collapse: collapse;
    }

    .tbl_tr {
        border-bottom: 1pt solid black;
    }

    .tbl_tr_top {
        border-bottom: 1pt solid black;
        border-top: 1pt solid black;
    }

    .wd_table {
        width: 10%;
    }
</style>

<title>Laba Rugi Summary</title>

<table width="100%" border="0" align="center" class="font-style">
    <tr>
        <!--<td rowspan="2" width="0%" height="10px"><img src="<?php echo base_url('assets/theme/adm2/img/logo.jpg'); ?>" style="width: 30px"></td>-->
        <td align="left" style="font-size:14px;font-style: italic;">PT MULIA SAWIT AGRO LESTARI</td>
    </tr>
    <tr>
        <td align="center" style="font-size:16px;font-weight:bold;">Income Statement<br /></td>
    </tr>
    <tr>
        <td align="center">
            Periode :
            <?php
            if ($bln == '01') {
                echo 'Januari';
            } else if ($bln == '02') {
                echo 'Februari';
            } else if ($bln == '03') {
                echo 'Maret';
            } else if ($bln == '04') {
                echo 'April';
            } else if ($bln == '05') {
                echo 'Mei';
            } else if ($bln == '06') {
                echo 'Juni';
            } else if ($bln == '07') {
                echo 'Juli';
            } else if ($bln == '08') {
                echo 'Agustus';
            } else if ($bln == '09') {
                echo 'September';
            } else if ($bln == '10') {
                echo 'Oktober';
            } else if ($bln == '11') {
                echo 'November';
            } else if ($bln == '12') {
                echo 'Desember';
            }
            echo ', ' . $thn;
            ?>
        </td>
    </tr>
</table>
<br>

<div style="padding-left:300px">

    <table width="70%" border="0" class="font-style">
        <tr>
            <td align="left" style="font-style: italic;">
                <table width="100%" border="0" align="center" class="font-styles">
                    <tr>
                        <td align="left" style="font-style: italic;">Generated By System MIPS - GL</td>
                    </tr>
                    <tr>
                        <td align="left" style="font-style: italic;">MIS - MSAL GROUP</td>
                    </tr>
                </table>
            </td>
            <td align="right" style="font-style: italic;">
                <div style="width: 100%;text-align: right;font-size: 10px" class="font-styles">
                    Tanggal : <?php echo date("m/d/Y"); ?>
                    <br>
                    Waktu : <?php
                            date_default_timezone_set("Asia/Bangkok");
                            echo date("h:i:s a", time()); ?>
                </div>
            </td>
        </tr>
    </table>
    <br>
    <table border="1" width="70%" class="font-style">
        <tbody>

            <!-- START PENDAPATAN -->
            <tr>
                <td style="font-weight:bold;height: 30px;font-size:15px">&nbsp;
                    PENDAPATAN
                    <!-- Revenue -->
                </td>
                <td>&nbsp;&nbsp; </td>
            </tr>
            <?php
            $tot_re;
            $total_laba_kotor = $tot_re - $tot_ex;
            $sum_revenue;

            foreach ($ic_revenue as $a) {
            ?>
                <tr>
                    <td>&nbsp; <?php echo $a['nama']; ?></td>
                    <td align="right">&nbsp;
                        <?php
                        if ($bln == '01') {
                            $sal_re = (($a['saldo01c']) + ($a['saldo01d']) * -1);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_re, 0));
                            $tot_re += $sal_re;
                        } else if ($bln == '02') {
                            $sal_re = (($a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d']) * -1);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_re, 0));
                            $tot_re += $sal_re;
                        } else if ($bln == '03') {
                            $sal_re = ($a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d']) * -1;
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_re, 0));
                            $tot_re += $sal_re;
                        } else if ($bln == '04') {
                            $sal_re = ($a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d']) * -1;
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_re, 0));
                            $tot_re += $sal_re;
                        } else if ($bln == '05') {
                            $sal_re = ($a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d']) * -1;
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_re, 0));
                            $tot_re += $sal_re;
                        } else if ($bln == '06') {
                            $sal_re = ($a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d']) * -1;
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_re, 0));
                            $tot_re += $sal_re;
                        } else if ($bln == '07') {
                            $sal_re = ($a['saldo07c'] + $a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d'] + $a['saldo07d']) * -1;
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_re, 0));
                            $tot_re += $sal_re;
                        } else if ($bln == '08') {
                            $sal_re = ($a['saldo08c'] + $a['saldo07c'] + $a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d'] + $a['saldo07d'] + $a['saldo08d']) * -1;
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_re, 0));
                            $tot_re += $sal_re;
                        } else if ($bln == '09') {
                            $sal_re = ($a['saldo09c'] + $a['saldo08c'] + $a['saldo07c'] + $a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d'] + $a['saldo07d'] + $a['saldo08d'] + $a['saldo09d']) * -1;
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_re, 0));
                            $tot_re += $sal_re;
                        } else if ($bln == '10') {
                            $sal_re = ($a['saldo10c'] + $a['saldo09c'] + $a['saldo08c'] + $a['saldo07c'] + $a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d'] + $a['saldo07d'] + $a['saldo08d'] + $a['saldo09d'] + $a['saldo10d']) * -1;
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_re, 0));
                            $tot_re += $sal_re;
                        } else if ($bln == '11') {
                            $sal_re = ($a['saldo11c'] + $a['saldo10c'] + $a['saldo09c'] + $a['saldo08c'] + $a['saldo07c'] + $a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d'] + $a['saldo07d'] + $a['saldo08d'] + $a['saldo09d'] + $a['saldo10d'] + $a['saldo11d']) * -1;
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_re, 0));
                            $tot_re += $sal_re;
                        } else if ($bln == '12') {
                            $sal_re = ($a['saldo12c'] + $a['saldo11c'] + $a['saldo10c'] + $a['saldo09c'] + $a['saldo08c'] + $a['saldo07c'] + $a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d'] + $a['saldo07d'] + $a['saldo08d'] + $a['saldo09d'] + $a['saldo10d'] + $a['saldo11d'] + $a['saldo12d']) * -1;
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_re, 0));
                            $tot_re += $sal_re;
                        }




                        // SUM REVENUE
                        if ($bln == '01') {
                            $sal_sum_re = (($a['saldo01c']) + ($a['saldo01d']) * -1);
                            $sum_revenue += $sal_sum_re;
                        } else if ($bln == '02') {
                            $sal_sum_re = (($a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d']) * -1);
                            $sum_revenue += $sal_sum_re;
                        } else if ($bln == '03') {
                            $sal_sum_re = (($a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d']) * -1);
                            $sum_revenue += $sal_sum_re;
                        } else if ($bln == '04') {
                            $sal_sum_re = (($a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d']) * -1);
                            $sum_revenue += $sal_sum_re;
                        } else if ($bln == '05') {
                            $sal_sum_re = (($a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d']) * -1);
                            $sum_revenue += $sal_sum_re;
                        } else if ($bln == '06') {
                            $sal_sum_re = (($a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d']) * -1);
                            $sum_revenue += $sal_sum_re;
                        } else if ($bln == '07') {
                            $sal_sum_re = (($a['saldo07c'] + $a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d'] + $a['saldo07d']) * -1);
                            $sum_revenue += $sal_sum_re;
                        } else if ($bln == '08') {
                            $sal_sum_re = (($a['saldo08c'] + $a['saldo07c'] + $a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d'] + $a['saldo07d'] + $a['saldo08d']) * -1);
                            $sum_revenue += $sal_sum_re;
                        } else if ($bln == '09') {
                            $sal_sum_re = (($a['saldo09c'] + $a['saldo08c'] + $a['saldo07c'] + $a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d'] + $a['saldo07d'] + $a['saldo08d'] + $a['saldo09d']) * -1);
                            $sum_revenue += $sal_sum_re;
                        } else if ($bln == '10') {
                            $sal_sum_re = (($a['saldo10c'] + $a['saldo09c'] + $a['saldo08c'] + $a['saldo07c'] + $a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d'] + $a['saldo07d'] + $a['saldo08d'] + $a['saldo09d'] + $a['saldo10d']) * -1);
                            $sum_revenue += $sal_sum_re;
                        } else if ($bln == '11') {
                            $sal_sum_re = (($a['saldo11c'] + $a['saldo10c'] + $a['saldo09c'] + $a['saldo08c'] + $a['saldo07c'] + $a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d'] + $a['saldo07d'] + $a['saldo08d'] + $a['saldo09d'] + $a['saldo10d'] + $a['saldo11d']) * -1);
                            $sum_revenue += $sal_sum_re;
                        } else if ($bln == '12') {
                            $sal_sum_re = (($a['saldo12c'] + $a['saldo11c'] + $a['saldo10c'] + $a['saldo09c'] + $a['saldo08c'] + $a['saldo07c'] + $a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d'] + $a['saldo07d'] + $a['saldo08d'] + $a['saldo09d'] + $a['saldo10d'] + $a['saldo11d'] + $a['saldo12d']) * -1);
                            $sum_revenue += $sal_sum_re;
                        }

                        ?>
                    </td>
                </tr>
            <?php
            }
            ?>
            <tr>
                <td style="font-weight:bold;height: 20px">&nbsp; <i>JUMLAH PENJUALAN</i> </td>
                <td align="right" style="font-weight:bold">&nbsp;
                    <i>
                        <?php
                        $ubahformat = preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_re, 0));
                        echo '<b>' . $ubahformat . '</b>';
                        ?>
                    </i>
                </td>
            </tr>
            <!-- START PENDAPATAN -->






            <!-- START HARGA POKOK PENJUALAN -->
            <tr>
                <td style="font-weight:bold;height: 30px;font-size:13px">&nbsp;
                    HARGA POKOK PENJUALAN
                    <!-- Revenue -->
                </td>
                <td>&nbsp;&nbsp; </td>
            </tr>
            <?php
            $sum_expensise;
            $tot_xe;
            foreach ($ic_expenses as $a) {
            ?>
                <tr>
                    <td>&nbsp; <?php echo $a['nama']; ?></td>
                    <td align="right">&nbsp;
                        <?php
                        if ($bln == '01') {
                            $sal_ex = ($a['saldo01d']) - ($a['saldo01c']);
                            $tot_ex += $sal_ex;
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                        } else if ($bln == '02') {
                            $sal_ex = ($a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c']);
                            $tot_ex += $sal_ex;
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                        } else if ($bln == '03') {
                            $sal_ex = ($a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c']);
                            $tot_ex += $sal_ex;
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                        } else if ($bln == '04') {
                            $sal_ex = ($a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c']);
                            $tot_ex += $sal_ex;
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                        } else if ($bln == '05') {
                            $sal_ex = ($a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c']);
                            $tot_ex += $sal_ex;
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                        } else if ($bln == '06') {
                            $sal_ex = ($a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c']);
                            $tot_ex += $sal_ex;
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                        } else if ($bln == '07') {
                            $sal_ex = ($a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c']);
                            $tot_ex += $sal_ex;
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                        } else if ($bln == '08') {
                            $sal_ex = ($a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c']);
                            $tot_ex += $sal_ex;
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                        } else if ($bln == '09') {
                            $sal_ex = ($a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c']);
                            $tot_ex += $sal_ex;
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                        } else if ($bln == '10') {
                            $sal_ex = ($a['saldo10d'] + $a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c'] + $a['saldo10c']);
                            $tot_ex += $sal_ex;
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                        } else if ($bln == '11') {
                            $sal_ex = ($a['saldo11d'] + $a['saldo10d'] + $a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c'] + $a['saldo10c'] + $a['saldo11c']);
                            $tot_ex += $sal_ex;
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                        } else if ($bln == '12') {
                            $sal_ex = ($a['saldo12d'] + $a['saldo11d'] + $a['saldo10d'] + $a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c'] + $a['saldo10c'] + $a['saldo11c'] + $a['saldo12c']);
                            $tot_ex += $sal_ex;
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                        }


                        //SUM EXPENSISE
                        if ($bln == '01') {
                            $sal_sum_ex = ($a['saldo01d']) - ($a['saldo01c']);
                            $sum_expensise += $sal_sum_ex;
                        } else if ($bln == '02') {
                            $sal_sum_ex = ($a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c']);
                            $sum_expensise += $sal_sum_ex;
                        } else if ($bln == '03') {
                            $sal_sum_ex = ($a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c']);
                            $sum_expensise += $sal_sum_ex;
                        } else if ($bln == '04') {
                            $sal_sum_ex = ($a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c']);
                            $sum_expensise += $sal_sum_ex;
                        } else if ($bln == '05') {
                            $sal_sum_ex = ($a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c']);
                            $sum_expensise += $sal_sum_ex;
                        } else if ($bln == '06') {
                            $sal_sum_ex = ($a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c']);
                            $sum_expensise  += $sal_sum_ex;
                        } else if ($bln == '07') {
                            $sal_sum_ex = ($a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c']);
                            $sum_expensise += $sal_sum_ex;
                        } else if ($bln == '08') {
                            $sal_sum_ex = ($a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c']);
                            $sum_expensise += $sal_sum_ex;
                        } else if ($bln == '09') {
                            $sal_sum_ex = ($a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c']);
                            $sum_expensise += $sal_sum_ex;
                        } else if ($bln == '10') {
                            $sal_sum_ex = ($a['saldo10d'] + $a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c'] + $a['saldo10c']);
                            $sum_expensise += $sal_sum_ex;
                        } else if ($bln == '11') {
                            $sal_sum_ex = ($a['saldo11d'] + $a['saldo10d'] + $a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c'] + $a['saldo10c'] + $a['saldo11c']);
                            $sum_expensise += $sal_sum_ex;
                        } else if ($bln == '12') {
                            $sal_sum_ex = ($a['saldo12d'] + $a['saldo11d'] + $a['saldo10d'] + $a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c'] + $a['saldo10c'] + $a['saldo11c'] + $a['saldo12c']);
                            $sum_expensise += $sal_sum_ex;
                        }

                        ?>
                    </td>
                </tr>
            <?php
            }
            ?>
            <tr>
                <td style="font-weight:bold;height: 20px">&nbsp; <i>JUMLAH HARGA POKOK PENJUALAN</i> </td>
                <td align="right">&nbsp;
                    <i>
                        <?php
                        $tota_exp += $sum_expensise;
                        echo '<b>' . number_format($sum_expensise, 0) . '</b>';
                        ?>
                    </i>
                </td>
            </tr>
            <!-- END HARGA POKOK PENJUALAN -->


            <tr>
                <td style="font-weight:bold;height: 30px;font-size: 14px">&nbsp;
                    LABA KOTOR
                    <!-- Other Expenses -->
                </td>
                <td align="right" style="font-weight:bold;font-size: 14px">&nbsp;&nbsp;<i>
                        <?php
                        $tot_labar_kotor = $tot_re - $sum_expensise;
                        echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_labar_kotor, 0));
                        //echo number_format($tot_labar_kotor,0);
                        ?></i></td>
            </tr>
            <tr>
                <td style="font-weight:bold;height: 30px;font-size:13px">&nbsp;
                    BIAYA OPERASIONAL
                    <!-- Revenue -->
                </td>
                <td>&nbsp;&nbsp; </td>
            </tr>

            <!-- START BIAYA PENJUALAN -->
            <tr>
                <td style="font-weight:bold;height: 30px">&nbsp;
                    BIAYA PENJUALAN
                    <!-- Expenses -->
                </td>
                <td>&nbsp;&nbsp; </td>
            </tr>
            <?php
            $tot_ex_bp;
            foreach ($ic_expenses_biaya_penjualan as $a) {
            ?>
                <tr>
                    <td>&nbsp; <?php echo $a['nama']; ?></td>
                    <td align="right">&nbsp;
                        <?php

                        if ($bln == '01') {
                            $sal_ex = ($a['saldo01d'] - $a['saldo01c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                            $tot_ex_bp += $sal_ex;
                        } else if ($bln == '02') {
                            $sal_ex = ($a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                            $tot_ex_bp += $sal_ex;
                        } else if ($bln == '03') {
                            $sal_ex = ($a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) + ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                            $tot_ex_bp += $sal_ex;
                        } else if ($bln == '04') {
                            $sal_ex = ($a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                            $tot_ex_bp += $sal_ex;
                        } else if ($bln == '05') {
                            $sal_ex = ($a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                            $tot_ex_bp += $sal_ex;
                        } else if ($bln == '06') {
                            $sal_ex = ($a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                            $tot_ex_bp += $sal_ex;
                        } else if ($bln == '07') {
                            $sal_ex = ($a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                            $tot_ex_bp += $sal_ex;
                        } else if ($bln == '08') {
                            $sal_ex = ($a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                            $tot_ex_bp += $sal_ex;
                        } else if ($bln == '09') {
                            $sal_ex = ($a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                            $tot_ex_bp += $sal_ex;
                        } else if ($bln == '10') {
                            $sal_ex = ($a['saldo10d'] + $a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c'] + $a['saldo10c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                            $tot_ex_bp += $sal_ex;
                        } else if ($bln == '11') {
                            $sal_ex = ($a['saldo11d'] + $a['saldo10d'] + $a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c'] + $a['saldo10c'] + $a['saldo11c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                            $tot_ex_bp += $sal_ex;
                        } else if ($bln == '12') {
                            $sal_ex = ($a['saldo12d'] + $a['saldo11d'] + $a['saldo10d'] + $a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c'] + $a['saldo10c'] + $a['saldo11c'] + $a['saldo12c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                            $tot_ex_bp += $sal_ex;
                        }

                        //        if($bln == '01'){
                        //            $sal_ex_bp = ($a['saldo01c']-$a['saldo01d'])*-1;
                        //            echo number_format($sal_ex_bp, 0);
                        //            $tot_ex_bp +=$sal_ex_bp; 
                        //        }else if($bln == '02'){
                        //            $sal_ex_bp = ($a['saldo02c']+$a['saldo01c'])+($a['saldo01d']+$a['saldo02d'])*-1;
                        //            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex_bp,0));
                        //            $tot_ex_bp +=$sal_ex_bp;
                        //        }else if($bln == '03'){
                        //            $sal_ex_bp = ($a['saldo03c']+$a['saldo02c']+$a['saldo01c'])+($a['saldo01d']+$a['saldo02d']+$a['saldo03d'])*-1;
                        //            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex_bp,0));
                        //            $tot_ex_bp +=$sal_ex_bp;
                        //        }else if($bln == '04'){
                        //            $sal_ex_bp = ($a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'])+($a['saldo01d']+$a['saldo02d']+$a['saldo03d']+$a['saldo04d'])*-1;
                        //            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex_bp,0));
                        //            $tot_ex_bp +=$sal_ex_bp;
                        //        }else if($bln == '05'){
                        //            $sal_ex_bp = ($a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'])+($a['saldo01d']+$a['saldo02d']+$a['saldo03d']+$a['saldo04d']+$a['saldo05d'])*-1;
                        //            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex_bp,0));
                        //            $tot_ex_bp +=$sal_ex_bp;
                        //        }else if($bln == '06'){
                        //           $sal_ex_bp = ($a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'])+($a['saldo01d']+$a['saldo02d']+$a['saldo03d']+$a['saldo04d']+$a['saldo05d']+$a['saldo06d'])*-1;
                        //           echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex_bp,0));
                        //           $tot_ex_bp +=$sal_ex_bp;
                        //        }else if($bln == '07'){
                        //            $sal_ex_bp = ($a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'])+($a['saldo01d']+$a['saldo02d']+$a['saldo03d']+$a['saldo04d']+$a['saldo05d']+$a['saldo06d']+$a['saldo07d'])*-1;
                        //            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex_bp,0));
                        //            $tot_ex_bp +=$sal_ex_bp;
                        //        }else if($bln == '08'){
                        //            $sal_ex_bp = ($a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'])+($a['saldo01d']+$a['saldo02d']+$a['saldo03d']+$a['saldo04d']+$a['saldo05d']+$a['saldo06d']+$a['saldo07d']+$a['saldo08d'])*-1;
                        //           echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex_bp,0));
                        //            $tot_ex_bp +=$sal_ex_bp;
                        //        }else if($bln == '09'){
                        //            $sal_ex_bp = ($a['saldo09c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'])+($a['saldo01d']+$a['saldo02d']+$a['saldo03d']+$a['saldo04d']+$a['saldo05d']+$a['saldo06d']+$a['saldo07d']+$a['saldo08d']+$a['saldo09d'])*-1;
                        //            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex_bp,0));
                        //            $tot_ex_bp +=$sal_ex_bp;
                        //        }else if($bln == '10'){
                        //            $sal_ex_bp = ($a['saldo10c']+$a['saldo09c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'])+($a['saldo01d']+$a['saldo02d']+$a['saldo03d']+$a['saldo04d']+$a['saldo05d']+$a['saldo06d']+$a['saldo07d']+$a['saldo08d']+$a['saldo09d']+$a['saldo10d'])*-1;
                        //            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex_bp,0));
                        //            $tot_ex_bp +=$sal_ex_bp;
                        //        }else if($bln == '11'){
                        //            $sal_ex_bp = ($a['saldo11c']+$a['saldo10c']+$a['saldo09c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'])+($a['saldo01d']+$a['saldo02d']+$a['saldo03d']+$a['saldo04d']+$a['saldo05d']+$a['saldo06d']+$a['saldo07d']+$a['saldo08d']+$a['saldo09d']+$a['saldo10d']+$a['saldo11d'])*-1;
                        //            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex_bp,0));
                        //            $tot_ex_bp +=$sal_ex_bp;
                        //        }else if($bln == '12'){
                        //            $sal_ex_bp = ($a['saldo12c']+$a['saldo11c']+$a['saldo10c']+$a['saldo09c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'])+($a['saldo01d']+$a['saldo02d']+$a['saldo03d']+$a['saldo04d']+$a['saldo05d']+$a['saldo06d']+$a['saldo07d']+$a['saldo08d']+$a['saldo09d']+$a['saldo10d']+$a['saldo11d']+$a['saldo12d'])*-1;
                        //            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex_bp,0));
                        //            $tot_ex_bp +=$sal_ex_bp;
                        //        }
                        ?>
                    </td>
                </tr>
            <?php
            }
            ?>
            <tr>
                <td style="font-weight:bold;height: 20px">&nbsp; <i>JUMLAH BIAYA PENJUALAN</i> </td>
                <td align="right" style="font-weight:bold">&nbsp;
                    <i>
                        <?php
                        echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_ex_bp, 0));
                        ?>
                    </i>
                </td>
            </tr>
            <!-- END BIAYA PENJUALAN -->



            <!-- START  BIAYA ADMINISTRATSI UMUM -->
            <tr>
                <td style="font-weight:bold;height: 30px">&nbsp;
                    BIAYA ADMINISTRASI UMUM
                    <!-- Expenses -->
                </td>
                <td>&nbsp;&nbsp; </td>
            </tr>
            <?php
            $tot_ixau;
            foreach ($ic_expenses_administrasi_umum as $a) {
            ?>
                <tr>
                    <td>&nbsp; <?php echo $a['nama']; ?></td>
                    <td align="right">&nbsp;
                        <?php

                        if ($bln == '01') {
                            $sal_ex = ($a['saldo01d'] - $a['saldo01c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                            $tot_ixau += $sal_ex;
                        } else if ($bln == '02') {
                            $sal_ex = ($a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                            $tot_ixau += $sal_ex;
                        } else if ($bln == '03') {
                            $sal_ex = ($a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                            $tot_ixau += $sal_ex;
                        } else if ($bln == '04') {
                            $sal_ex = ($a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                            $tot_ixau += $sal_ex;
                        } else if ($bln == '05') {
                            $sal_ex = ($a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                            $tot_ixau += $sal_ex;
                        } else if ($bln == '06') {
                            $sal_ex = ($a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                            $tot_ixau += $sal_ex;
                        } else if ($bln == '07') {
                            $sal_ex = ($a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                            $tot_ixau += $sal_ex;
                        } else if ($bln == '08') {
                            $sal_ex = ($a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                            $tot_ixau += $sal_ex;
                        } else if ($bln == '09') {
                            $sal_ex = ($a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                            $tot_ixau += $sal_ex;
                        } else if ($bln == '10') {
                            $sal_ex = ($a['saldo10d'] + $a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c'] + $a['saldo10c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                            $tot_ixau += $sal_ex;
                        } else if ($bln == '11') {
                            $sal_ex = ($a['saldo11d'] + $a['saldo10d'] + $a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c'] + $a['saldo10c'] + $a['saldo11c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                            $tot_ixau += $sal_ex;
                        } else if ($bln == '12') {
                            $sal_ex = ($a['saldo12d'] + $a['saldo11d'] + $a['saldo10d'] + $a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c'] + $a['saldo10c'] + $a['saldo11c'] + $a['saldo12c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ex, 0));
                            $tot_ixau += $sal_ex;
                        }

                        //        if($bln == '01'){
                        //            $sal_ixau = ($a['saldo01c']-$a['saldo01d'])*-1;
                        //            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ixau,0));
                        //            $tot_ixau +=$sal_ixau; 
                        //        }else if($bln == '02'){
                        //            $sal_ixau = (($a['saldo02c']+$a['saldo01c'])+($a['saldo01d']+$a['saldo02d'])*-1);
                        //            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ixau,0));
                        //            $tot_ixau +=$sal_ixau;
                        //        }else if($bln == '03'){
                        //            $sal_ixau = ($a['saldo03c']+$a['saldo02c']+$a['saldo01c'])+($a['saldo01d']+$a['saldo02d']+$a['saldo03d'])*-1;
                        //            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ixau,0));
                        //            $tot_ixau +=$sal_ixau;
                        //        }else if($bln == '04'){
                        //            $sal_ixau = ($a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'])+($a['saldo01d']+$a['saldo02d']+$a['saldo03d']+$a['saldo04d'])*-1;
                        //            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ixau,0));
                        //            $tot_ixau +=$sal_ixau;
                        //        }else if($bln == '05'){
                        //            $sal_ixau = ($a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'])+($a['saldo01d']+$a['saldo02d']+$a['saldo03d']+$a['saldo04d']+$a['saldo05d'])*-1;
                        //            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ixau,0));
                        //            $tot_ixau +=$sal_ixau;
                        //        }else if($bln == '06'){
                        //           $sal_ixau = ($a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'])+($a['saldo01d']+$a['saldo02d']+$a['saldo03d']+$a['saldo04d']+$a['saldo05d']+$a['saldo06d'])*-1;
                        //           echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ixau,0));
                        //           $tot_ixau +=$sal_ixau;
                        //        }else if($bln == '07'){
                        //            $sal_ixau = ($a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'])+($a['saldo01d']+$a['saldo02d']+$a['saldo03d']+$a['saldo04d']+$a['saldo05d']+$a['saldo06d']+$a['saldo07d'])*-1;
                        //            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ixau,0));
                        //            $tot_ixau +=$sal_ixau;
                        //        }else if($bln == '08'){
                        //            $sal_ixau = ($a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'])+($a['saldo01d']+$a['saldo02d']+$a['saldo03d']+$a['saldo04d']+$a['saldo05d']+$a['saldo06d']+$a['saldo07d']+$a['saldo08d'])*-1;
                        //            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ixau,0));
                        //            $tot_ixau +=$sal_ixau;
                        //        }else if($bln == '09'){
                        //            $sal_ixau = ($a['saldo09c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'])+($a['saldo01d']+$a['saldo02d']+$a['saldo03d']+$a['saldo04d']+$a['saldo05d']+$a['saldo06d']+$a['saldo07d']+$a['saldo08d']+$a['saldo09d'])*-1;
                        //            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ixau,0));
                        //            $tot_ixau +=$sal_ixau;
                        //        }else if($bln == '10'){
                        //            $sal_ixau = ($a['saldo10c']+$a['saldo09c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'])+($a['saldo01d']+$a['saldo02d']+$a['saldo03d']+$a['saldo04d']+$a['saldo05d']+$a['saldo06d']+$a['saldo07d']+$a['saldo08d']+$a['saldo09d']+$a['saldo10d'])*-1;
                        //            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ixau,0));
                        //            $tot_ixau +=$sal_ixau;
                        //        }else if($bln == '11'){
                        //            $sal_ixau = ($a['saldo11c']+$a['saldo10c']+$a['saldo09c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'])+($a['saldo01d']+$a['saldo02d']+$a['saldo03d']+$a['saldo04d']+$a['saldo05d']+$a['saldo06d']+$a['saldo07d']+$a['saldo08d']+$a['saldo09d']+$a['saldo10d']+$a['saldo11d'])*-1;
                        //            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ixau,0));
                        //            $tot_ixau +=$sal_ixau;
                        //        }else if($bln == '12'){
                        //            $sal_ixau = ($a['saldo12c']+$a['saldo11c']+$a['saldo10c']+$a['saldo09c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'])+($a['saldo01d']+$a['saldo02d']+$a['saldo03d']+$a['saldo04d']+$a['saldo05d']+$a['saldo06d']+$a['saldo07d']+$a['saldo08d']+$a['saldo09d']+$a['saldo10d']+$a['saldo11d']+$a['saldo12d'])*-1;
                        //            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_ixau,0));
                        //            $tot_ixau +=$sal_ixau;
                        //        }
                        ?>
                    </td>
                </tr>
            <?php
            }
            ?>
            <tr>
                <td style="font-weight:bold;height: 20px">&nbsp; <i>JUMLAH BIAYA ADMINISTRASI UMUM</i> </td>
                <td align="right" style="font-weight:bold">&nbsp;
                    <i>
                        <?php

                        echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_ixau, 0));
                        ?>
                    </i>
                </td>
            </tr>
            <!-- END BIAYA ADMINISTRATSI UMUM -->


            <tr>
                <td style="font-weight:bold;height: 40px;font-size: 13px">&nbsp;TOTAL BIAYA OPERASIONAL </td>
                <td align="right" style="font-weight:bold;height: 15px;font-size: 13px">&nbsp;
                    <i>
                        <?php
                        $tot_jum_biaya_operasionals = $tot_ex_bp + $tot_ixau;
                        echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_jum_biaya_operasionals, 0));
                        ?>
                    </i>
                </td>
            </tr>

            <!-- BIAYA RUNNING Expensise -->
            <?php
            $tot_exbr;
            foreach ($ic_expenses_biaya_running as $a) {
            ?>
                <tr>
                    <td>&nbsp; <?php echo $a['nama']; ?></td>
                    <td align="right">&nbsp;
                        <?php
                        if ($bln == '01') {
                            $sal_exbr = ($a['saldo01d'] - $a['saldo01c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_exbr, 0));
                            $tot_exbr += $sal_exbr;
                        } else if ($bln == '02') {
                            $sal_exbr = ($a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_exbr, 0));
                            $tot_exbr += $sal_exbr;
                        } else if ($bln == '03') {
                            $sal_exbr = ($a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) + ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_exbr, 0));
                            $tot_exbr += $sal_exbr;
                        } else if ($bln == '04') {
                            $sal_exbr = ($a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_exbr, 0));
                            $tot_exbr += $sal_exbr;
                        } else if ($bln == '05') {
                            $sal_exbr = ($a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_exbr, 0));
                            $tot_exbr += $sal_exbr;
                        } else if ($bln == '06') {
                            $sal_exbr = ($a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_exbr, 0));
                            $tot_exbr += $sal_exbr;
                        } else if ($bln == '07') {
                            $sal_exbr = ($a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_exbr, 0));
                            $tot_exbr += $sal_exbr;
                        } else if ($bln == '08') {
                            $sal_exbr = ($a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_exbr, 0));
                            $tot_exbr += $sal_exbr;
                        } else if ($bln == '09') {
                            $sal_exbr = ($a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_exbr, 0));
                            $tot_exbr += $sal_exbr;
                        } else if ($bln == '10') {
                            $sal_exbr = ($a['saldo10d'] + $a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c'] + $a['saldo10c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_exbr, 0));
                            $tot_exbr += $sal_exbr;
                        } else if ($bln == '11') {
                            $sal_exbr = ($a['saldo11d'] + $a['saldo10d'] + $a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c'] + $a['saldo10c'] + $a['saldo11c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_exbr, 0));
                            $tot_exbr += $sal_exbr;
                        } else if ($bln == '12') {
                            $sal_exbr = ($a['saldo12d'] + $a['saldo11d'] + $a['saldo10d'] + $a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c'] + $a['saldo10c'] + $a['saldo11c'] + $a['saldo12c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_exbr, 0));
                            $tot_exbr += $sal_exbr;
                        }
                        ?>
                    </td>
                </tr>
            <?php
            }
            ?>

            <!-- START PENDAPATAN LAINNYA -->
            <tr>
                <td style="font-weight:bold;height: 30px;font-size:13px">&nbsp;
                    PENDAPATAN LAINNYA
                    <!-- Other Revenue -->
                </td>
                <td>&nbsp;&nbsp; </td>
            </tr>
            <?php
            $tot_oer;
            $sum_ot_revenue;
            foreach ($ic_other_revenue as $a) {
            ?>
                <tr>
                    <td>&nbsp; <?php echo $a['nama']; ?></td>
                    <td align="right">&nbsp;
                        <?php
                        if ($bln == '01') {
                            $sal_oer = (($a['saldo01c']) + ($a['saldo01d']) * -1);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_oer, 0));
                            $tot_oer += $sal_oer;
                        } else if ($bln == '02') {
                            $sal_oer = (($a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d']) * -1);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_oer, 0));
                            $tot_oer += $sal_oer;
                        } else if ($bln == '03') {
                            $sal_oer = (($a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d']) * -1);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_oer, 0));
                            $tot_oer += $sal_oer;
                        } else if ($bln == '04') {
                            $sal_oer = (($a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d']) * -1);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_oer, 0));
                            $tot_oer += $sal_oer;
                        } else if ($bln == '05') {
                            $sal_oer = (($a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d']) * -1);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_oer, 0));
                            $tot_oer += $sal_oer;
                        } else if ($bln == '06') {
                            $sal_oer = (($a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d']) * -1);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_oer, 0));
                            $tot_oer += $sal_oer;
                        } else if ($bln == '07') {
                            $sal_oer = (($a['saldo07c'] + $a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d'] + $a['saldo07d']) * -1);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_oer, 0));
                            $tot_oer += $sal_oer;
                        } else if ($bln == '08') {
                            $sal_oer = (($a['saldo08c'] + $a['saldo07c'] + $a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d'] + $a['saldo07d'] + $a['saldo08d']) * -1);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_oer, 0));
                            $tot_oer += $sal_oer;
                        } else if ($bln == '09') {
                            $sal_oer = (($a['saldo09c'] + $a['saldo08c'] + $a['saldo07c'] + $a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d'] + $a['saldo07d'] + $a['saldo08d'] + $a['saldo09d']) * -1);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_oer, 0));
                            $tot_oer += $sal_oer;
                        } else if ($bln == '10') {
                            $sal_oer = (($a['saldo10c'] + $a['saldo09c'] + $a['saldo08c'] + $a['saldo07c'] + $a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d'] + $a['saldo07d'] + $a['saldo08d'] + $a['saldo09d'] + $a['saldo10d']) * -1);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_oer, 0));
                            $tot_oer += $sal_oer;
                        } else if ($bln == '11') {
                            $sal_oer = (($a['saldo11c'] + $a['saldo10c'] + $a['saldo09c'] + $a['saldo08c'] + $a['saldo07c'] + $a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d'] + $a['saldo07d'] + $a['saldo08d'] + $a['saldo09d'] + $a['saldo10d'] + $a['saldo11d']) * -1);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_oer, 0));
                            $tot_oer += $sal_oer;
                        } else if ($bln == '12') {
                            $sal_oer = (($a['saldo12c'] + $a['saldo11c'] + $a['saldo10c'] + $a['saldo09c'] + $a['saldo08c'] + $a['saldo07c'] + $a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d'] + $a['saldo07d'] + $a['saldo08d'] + $a['saldo09d'] + $a['saldo10d'] + $a['saldo11d'] + $a['saldo12d']) * -1);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_oer, 0));
                            $tot_oer += $sal_oer;
                        }





                        // SUM REVENUE
                        if ($bln == '01') {
                            $sal_sum_ot_re = (($a['saldo01c']) + ($a['saldo01d']) * -1);
                            $sum_ot_revenue += $sal_sum_ot_re;
                        } else if ($bln == '02') {
                            $sal_sum_ot_re = (($a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d']) * -1);
                            $sum_ot_revenue += $sal_sum_ot_re;
                        } else if ($bln == '03') {
                            $sal_sum_ot_re = (($a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d']) * -1);
                            $sum_ot_revenue += $sal_sum_ot_re;
                        } else if ($bln == '04') {
                            $sal_sum_ot_re = (($a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d']) * -1);
                            $sum_ot_revenue += $sal_sum_ot_re;
                        } else if ($bln == '05') {
                            $sal_sum_ot_re = (($a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d']) * -1);
                            $sum_ot_revenue += $sal_sum_ot_re;
                        } else if ($bln == '06') {
                            $sal_sum_ot_re = (($a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d']) * -1);
                            $sum_ot_revenue += $sal_sum_ot_re;
                        } else if ($bln == '07') {
                            $sal_sum_ot_re = (($a['saldo07c'] + $a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d'] + $a['saldo07d']) * -1);
                            $sum_ot_revenue += $sal_sum_ot_re;
                        } else if ($bln == '08') {
                            $sal_sum_ot_re = (($a['saldo08c'] + $a['saldo07c'] + $a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d'] + $a['saldo07d'] + $a['saldo08d']) * -1);
                            $sum_ot_revenue += $sal_sum_ot_re;
                        } else if ($bln == '09') {
                            $sal_sum_ot_re = (($a['saldo09c'] + $a['saldo08c'] + $a['saldo07c'] + $a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d'] + $a['saldo07d'] + $a['saldo08d'] + $a['saldo09d']) * -1);
                            $sum_ot_revenue += $sal_sum_ot_re;
                        } else if ($bln == '10') {
                            $sal_sum_ot_re = (($a['saldo10c'] + $a['saldo09c'] + $a['saldo08c'] + $a['saldo07c'] + $a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d'] + $a['saldo07d'] + $a['saldo08d'] + $a['saldo09d'] + $a['saldo10d']) * -1);
                            $sum_ot_revenue += $sal_sum_ot_re;
                        } else if ($bln == '11') {
                            $sal_sum_ot_re = (($a['saldo11c'] + $a['saldo10c'] + $a['saldo09c'] + $a['saldo08c'] + $a['saldo07c'] + $a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d'] + $a['saldo07d'] + $a['saldo08d'] + $a['saldo09d'] + $a['saldo10d'] + $a['saldo11d']) * -1);
                            $sum_ot_revenue += $sal_sum_ot_re;
                        } else if ($bln == '12') {
                            $sal_sum_ot_re = (($a['saldo12c'] + $a['saldo11c'] + $a['saldo10c'] + $a['saldo09c'] + $a['saldo08c'] + $a['saldo07c'] + $a['saldo06c'] + $a['saldo05c'] + $a['saldo04c'] + $a['saldo03c'] + $a['saldo02c'] + $a['saldo01c']) + ($a['saldo01d'] + $a['saldo02d'] + $a['saldo03d'] + $a['saldo04d'] + $a['saldo05d'] + $a['saldo06d'] + $a['saldo07d'] + $a['saldo08d'] + $a['saldo09d'] + $a['saldo10d'] + $a['saldo11d'] + $a['saldo12d']) * -1);
                            $sum_ot_revenue += $sal_sum_ot_re;
                        }

                        ?>
                    </td>
                </tr>
            <?php
            }
            ?>
            <tr>
                <td style="font-weight:bold;height: 20px">&nbsp; <i>JUMLAH PENDAPATAN LAINNYA</i> </td>
                <td align="right" style="font-weight:bold">&nbsp;
                    <i>
                        <?php
                        echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_oer, 0));
                        ?>
                    </i>
                </td>
            </tr>
            <!-- END PENDAPATAN LAINNYA -->





            <!-- START BIAYA LAINNYA -->
            <tr>
                <td style="font-weight:bold;height: 30px;font-size:13px">&nbsp;
                    BIAYA LAINNYA
                    <!-- Other Revenue -->
                </td>
                <td>&nbsp;&nbsp; </td>
            </tr>
            <?php
            $tot_oex;
            $sum_ot_expensise;
            foreach ($ic_other_expenses as $a) {
            ?>
                <tr>
                    <td>&nbsp; <?php echo $a['nama']; ?></td>
                    <td align="right">&nbsp;
                        <?php
                        if ($bln == '01') {
                            $sal_oex = ($a['saldo01d'] - $a['saldo01c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_oex, 0));
                            $tot_oex += $sal_oex;
                        } else if ($bln == '02') {
                            $sal_oex = ($a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_oex, 0));
                            $tot_oex += $sal_oex;
                        } else if ($bln == '03') {
                            $sal_oex = ($a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_oex, 0));
                            $tot_oex += $sal_oex;
                        } else if ($bln == '04') {
                            $sal_oex = ($a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_oex, 0));
                            $tot_oex += $sal_oex;
                        } else if ($bln == '05') {
                            $sal_oex = ($a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_oex, 0));
                            $tot_oex += $sal_oex;
                        } else if ($bln == '06') {
                            $sal_oex = ($a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_oex, 0));
                            $tot_oex += $sal_oex;
                        } else if ($bln == '07') {
                            $sal_oex = ($a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_oex, 0));
                            $tot_oex += $sal_oex;
                        } else if ($bln == '08') {
                            $sal_oex = ($a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_oex, 0));
                            $tot_oex += $sal_oex;
                        } else if ($bln == '09') {
                            $sal_oex = ($a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_oex, 0));
                            $tot_oex += $sal_oex;
                        } else if ($bln == '10') {
                            $sal_oex = ($a['saldo10d'] + $a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c'] + $a['saldo10c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_oex, 0));
                            $tot_oex += $sal_oex;
                        } else if ($bln == '11') {
                            $sal_oex = ($a['saldo11d'] + $a['saldo10d'] + $a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c'] + $a['saldo10c'] + $a['saldo11c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_oex, 0));
                            $tot_oex += $sal_oex;
                        } else if ($bln == '12') {
                            $sal_oex = ($a['saldo12d'] + $a['saldo11d'] + $a['saldo10d'] + $a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c'] + $a['saldo10c'] + $a['saldo11c'] + $a['saldo12c']);
                            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($sal_oex, 0));
                            $tot_oex += $sal_oex;
                        }




                        //SUM OTHER EXPENSISE
                        if ($bln == '01') {
                            $sal_sum_ot_ex = ($a['saldo01d'] - $a['saldo01c']);
                            $sum_ot_expensise += $sal_sum_ot_ex;
                        } else if ($bln == '02') {
                            $sal_sum_ot_ex = ($a['saldo02d'] + $a['saldo01d']) - ($a['saldo01c'] + $a['saldo02c']);
                            $sum_ot_expensise += $sal_sum_ot_ex;
                        } else if ($bln == '03') {
                            $sal_sum_ot_ex = ($a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) + ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c']);
                            $sum_ot_expensise += $sal_sum_ot_ex;
                        } else if ($bln == '04') {
                            $sal_sum_ot_ex = ($a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) + ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c']);
                            $sum_ot_expensise += $sal_sum_ot_ex;
                        } else if ($bln == '05') {
                            $sal_sum_ot_ex = ($a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) + ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c']);
                            $sum_ot_expensise += $sal_sum_ot_ex;
                        } else if ($bln == '06') {
                            $sal_sum_ot_ex = ($a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) + ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c']);
                            $sum_ot_expensise  += $sal_sum_ot_ex;
                        } else if ($bln == '07') {
                            $sal_sum_ot_ex = ($a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) + ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c']);
                            $sum_ot_expensise += $sal_sum_ot_ex;
                        } else if ($bln == '08') {
                            $sal_sum_ot_ex = ($a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) + ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c']);
                            $sum_ot_expensise += $sal_sum_ot_ex;
                        } else if ($bln == '09') {
                            $sal_sum_ot_ex = ($a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) + ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c']);
                            $sum_ot_expensise += $sal_sum_ot_ex;
                        } else if ($bln == '10') {
                            $sal_sum_ot_ex = ($a['saldo10d'] + $a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) + ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c'] + $a['saldo10c']);
                            $sum_ot_expensise += $sal_sum_ot_ex;
                        } else if ($bln == '11') {
                            $sal_sum_ot_ex = ($a['saldo11d'] + $a['saldo10d'] + $a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) + ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c'] + $a['saldo10c'] + $a['saldo11c']);
                            $sum_ot_expensise += $sal_sum_ot_ex;
                        } else if ($bln == '12') {
                            $sal_sum_ot_ex = ($a['saldo12d'] + $a['saldo11d'] + $a['saldo10d'] + $a['saldo09d'] + $a['saldo08d'] + $a['saldo07d'] + $a['saldo06d'] + $a['saldo05d'] + $a['saldo04d'] + $a['saldo03d'] + $a['saldo02d'] + $a['saldo01d']) + ($a['saldo01c'] + $a['saldo02c'] + $a['saldo03c'] + $a['saldo04c'] + $a['saldo05c'] + $a['saldo06c'] + $a['saldo07c'] + $a['saldo08c'] + $a['saldo09c'] + $a['saldo10c'] + $a['saldo11c'] + $a['saldo12c']);
                            $sum_ot_expensise += $sal_sum_ot_ex;
                        }
                        ?>
                    </td>
                </tr>
            <?php
            }
            ?>
            <tr>
                <td style="font-weight:bold;height: 20px">&nbsp; <i>JUMLAH BIAYA LAINNYA</i> </td>
                <td align="right" style="font-weight:bold">&nbsp;
                    <i>
                        <?php
                        echo '<b>' . preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_oex, 0)) . '</b>';
                        ?>
                    </i>
                </td>
            </tr>
            <!-- END BIAYA LAINNYA -->




            <tr>
            <tr>
                <td style="font-weight:bold;height: 30px;font-size: 13px">&nbsp;
                    LABA RUGI SEBELUM PAJAK
                    <!-- Other Expenses -->
                </td>
                <td align="right" style="height: 30px;font-size: 13px">&nbsp;&nbsp;
                    <span style="font-weight:bold">
                        <?php
                        //$tot_labarugi_bersih = $sum_revenue-$sum_expensise;
                        //$laba_rugi_mmop = ($sum_expensise+$sum_ot_expensise+$tot_ex+$tot_ex_bp+$tot_ixau+$tot_exbr+$tot_oex) - ($sum_revenue+$sum_ot_revenue);
                        //(Laba Kotor - Total Biaya Operasional - biaya lainnya) + jumlah pendapatan lainnya
                        //$tot_labarugi_sebelum_panak = $sum_revenue-$sum_expensise;
                        //$SSS = $tot_ex_bp+$tot_ixau;
                        //$tot_labarugi_sebelum_pajak = ($tot_labar_kotor-$SSS-$tot_oex)+$tot_oer;

                        $reven = $sum_revenue + $sum_ot_revenue;
                        $expen = $tot_ex + $tot_ex_bp + $tot_ixau + $tot_exbr + $tot_oex;
                        echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($reven - $expen, 0));
                        //echo number_format($reven-$expen,0);
                        ?>
                    </span>
                </td>
            </tr>

            <tr>
                <td style="font-weight:bold;height: 30px;font-size: 14px">&nbsp;
                    LABA(RUGI) BERSIH
                    <!-- Other Expenses -->
                </td>
                <td align="right" style="font-weight:bold;font-size: 14px">&nbsp;&nbsp;
                    <?php
                    //echo number_format($tot_labarugi_sebelum_pajak);
                    ?>
                    <?php
                    echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($reven - $expen, 0));
                    ?>
                </td>
            </tr>
        </tbody>
    </table>

</div>