<style>
 table.blueTable {
  border: 1px solid #AAAAAA;
  background-color: white;
  width: 100%;
  text-align: left;
  border-collapse: collapse;
}
table.blueTable td, table.blueTable th {
  border: 1px solid #AAAAAA;
  padding: 3px 2px;
}
table.blueTable tbody td {
  font-size: 13px;
}
table.blueTable tr:nth-child(even) {
  background: white;
}
table.blueTable thead {
  background: white;
  background: -moz-linear-gradient(top, #5592bb 0%, #327cad 66%, #1C6EA4 100%);
  background: -webkit-linear-gradient(top, #5592bb 0%, #327cad 66%, #1C6EA4 100%);
  background: linear-gradient(to bottom, #5592bb 0%, #327cad 66%, #1C6EA4 100%);
  border-bottom: 2px solid #FFFFFF;
}
table.blueTable thead th {
  font-size: 15px;
  font-weight: bold;
  color: black;
  border-left: 1px solid #1C6EA4;
}
table.blueTable thead th:first-child {
  border-left: none;
}

table.blueTable tfoot {
  font-size: 14px;
  font-weight: bold;
  color: #FFFFFF;
  background: white;
  background: -moz-linear-gradient(top, #dcebf7 0%, #d4e6f6 66%, #D0E4F5 100%);
  background: -webkit-linear-gradient(top, #dcebf7 0%, #d4e6f6 66%, #D0E4F5 100%);
  background: linear-gradient(to bottom, #dcebf7 0%, #d4e6f6 66%, #D0E4F5 100%);
  border-top: 2px solid #444444;
}
table.blueTable tfoot td {
  font-size: 14px;
}
table.blueTable tfoot .links {
  text-align: right;
}
table.blueTable tfoot .links a{
  display: inline-block;
  background: white;
  color: #FFFFFF;
  padding: 2px 8px;
  border-radius: 5px;
}
.fontsize_global_header{
  font-size: 7px;
}
.font-styles{
    font-family: Verdana, Geneva, sans-serif;
}
</style>



<table width="100%" border="0" align="center" class="font-styles">
    <tr>
        <td rowspan="2" width="0%" height="10px"><img src="<?php echo base_url('assets/theme/adm2/img/logo.jpg');?>" style="width: 50px"></td>
        <td align="center" style="font-size:25px;">PT Mulia Sawit Agro Lestari</td>
    </tr>
<!--    <tr>
        <td align="center">Jl. Radio Dalam Raya No.87A, RT.005/RW.014, Gandaria Utara, Kebayoran Baru,  JakartaSelatan, DKI Jakarta Raya-12140 <br /> Telp : 021-7231999, 7202418 (Hunting) <br /> Fax : 021-7231819
        </td>
    </tr>-->
</table>

<hr>

<div style="width: 100%;text-align: center;" class="font-styles">
	<span style="font-size: 18px">Laporan Register Voucher</span>
	<br>
        <?php 
            if($this->uri->segment(5) == 0){
        ?>
            <span style="font-size: 14px">Periode : <?php echo $this->uri->segment(3);?> s/d <?php echo $this->uri->segment(4);?></span>
        <?php 
            }else{
            
        ?>
            <span style="font-size: 14px">Periode ini : <?php echo $bulan;?> <?php echo $tahun;?></span>
        <?php 
        }
        ?>
	
</div>

<br>
<table class="blueTable font-styles">
<thead>
    <tr>
<th>TGL</th>
<th>NO.VOUC</th>
<th>NO.REF</th>
<th>KEPADA/DARI</th>
<th>KETERANGAN</th>
<th>NILAI</th>
</tr>
</thead>
<tbody>
<?php 
$nos = 0+1;

foreach($res_data as $a){
    //$a['nama']
?>
    
<tr>
<td width="100px" align="center"><?php echo $a['TGL'];?></td>
<td width="100px"><?php echo $a['VOUCNO'];?></td>
<td width="100px"><?php echo $a['KODE_REF'];?></td>
<td align="left" width="300px"><?php echo $a['FROM'];?></td>
<td align="left" width="300px"><?php echo $a['REMARKS'];?></td>
<td align="right" width="150px"><?php echo $a['AMOUNT_F'];?></td>
</tr>
<?php
$nos++;
}
?>
<tr>
</tbody>
</table>


<br>
<table width="100%" border="0" align="center" class="font-styles">
    <tr>
        <td align="left" style="font-style: italic;">Generated By System MIPS - Module Cash & Bank</td>
    </tr>
    <tr>
        <td align="left" style="font-style: italic;">MIS - MSAL GROUP</td>
    </tr>
</table>

<div style="width: 100%;text-align: right;font-size: 12px" class="font-styles">
  Tanggal : <?php echo date("m/d/Y");?>
  <br>
  Waktu   : <?php 
  date_default_timezone_set("Asia/Bangkok");
  echo date("h:i:s a",time());?>
</div>