<?php 
$prd = $this->uri->segment(3);
$thn = substr($prd, 0, 4);
$bln = substr($prd, 4, 6);
$account_labarugi = '504500000000000';
?>
<style>
.spinner-wrapper {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: #ff6347;
    z-index: 999999;
}
body {
    font-family: Verdana, Geneva, sans-serif;
}
table {
    font-family: Arial, Helvetica, sans-serif;
    font-size: 12px;
    border-collapse: collapse;
}
.tbl_tr{
  border-bottom:1pt solid black;
}
.tbl_tr_top{
  border-bottom:1pt solid black;
  border-top:1pt solid black;
}
.wd_table{
    width:10%;
}
</style>

<table width="100%" border="0" align="center" class="font-style">
    <tr>
        <!--<td rowspan="2" width="0%" height="10px"><img src="<?php echo base_url('assets/theme/adm2/img/logo.jpg');?>" style="width: 30px"></td>-->
        <td align="left" style="font-size:14px;font-style: italic;">PT MULIA SAWIT AGRO LESTARI</td>
    </tr>
    <tr>
        <td align="center" style="font-size:16px;font-weight:bold;">Balance Sheet<br /></td>
    </tr>
    <tr>
    <td align="center">
      Periode : 
        <?php 
            if($bln == 01){
                echo 'Januari';
            }else if($bln == 02){
                echo 'Februari';
            }else if($bln == 03){
                echo 'Maret';
            }else if($bln == 04){
                echo 'April';
            }else if($bln == 05){
                echo 'Mei';
            }else if($bln == 06){
                echo 'Juni';
            }else if($bln == 07){
                echo 'Juli';
            }else if($bln == 08){
                echo 'September';
            }else if($bln == 09){
                echo 'Oktober';
            }else if($bln == 10){
                echo 'November';
            }else if($bln == 11){
                echo 'Desember';
            }
            echo ', '.$thn;
        ?>
    </td>
    </tr>
</table>
<br>

<div style="padding-left:300px">
   
<table width="70%" border="0" class="font-style">
    <tr>
        <td align="left" style="font-style: italic;">
            <table width="100%" border="0" align="center" class="font-styles">
                <tr>
                    <td align="left" style="font-style: italic;">Generated By System MIPS - GL</td>
                </tr>
                <tr>
                    <td align="left" style="font-style: italic;">MIS - MSAL GROUP</td>
                </tr>
            </table>
        </td>
        <td align="right" style="font-style: italic;">
            <div style="width: 100%;text-align: right;font-size: 10px" class="font-styles">
                Tanggal : <?php echo date("m/d/Y");?>
                <br>
                Waktu   : <?php 
                date_default_timezone_set("Asia/Bangkok");
                echo date("h:i:s a",time());?>
            </div>
        </td>
    </tr>
</table>      
<br>    
<table border="1" width="70%" class="font-style" >
<tbody>
    
<!-- START PENDAPATAN -->    
<tr>
    <td style="font-weight:bold;height: 30px;font-size:14px">&nbsp;
        ASET LANCAR <!-- Revenue -->
    </td>
    <td>&nbsp;&nbsp; </td>
</tr>
<?php 
$tot_aset_lancar;
foreach ($aset_lancar as $a){
?>
<tr>
    <td>&nbsp; <?php echo $a['nama'];?></td>
    <td align="right">&nbsp;
    <?php 
        if($bln == '01'){
            $cr_aset_lancar = $a['yearc']+$a['saldo01c'];
        }else if($bln == '02'){
            $cr_aset_lancar = $a['yearc']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '03'){
            $cr_aset_lancar = $a['yearc']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '04'){
            $cr_aset_lancar = $a['yearc']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '05'){
            $cr_aset_lancar = $a['yearc']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '06'){
            $cr_aset_lancar = $a['yearc']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '07'){
            $cr_aset_lancar = $a['yearc']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '08'){
            $cr_aset_lancar = $a['yearc']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '09'){
            $cr_aset_lancar = $a['yearc']+$a['saldo09c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '10'){
            $cr_aset_lancar = $a['yearc']+$a['saldo10c']+$a['saldo09c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '11'){
            $cr_aset_lancar = $a['yearc']+$a['saldo11c']+$a['saldo10c']+$a['saldo09c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '12'){
            $cr_aset_lancar = $a['yearc']+$a['saldo12c']+$a['saldo11c']+$a['saldo10c']+$a['saldo09c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }
        
        
        
        
        if($bln == '01'){
            $db_aset_lancar = $a['yeard']+$a['saldo01d'];
        }else if($bln == '02'){
            $db_aset_lancar = $a['yeard']+$a['saldo02d']+$a['saldo01'];
        }else if($bln == '03'){
            $db_aset_lancar = $a['yeard']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '04'){
            $db_aset_lancar = $a['yeard']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '05'){
            $db_aset_lancar = $a['yeard']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '06'){
           $db_aset_lancar = $a['yeard']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '07'){
           $db_aset_lancar = $a['yeard']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '08'){
            $db_aset_lancar = $a['yeard']+$a['saldo08d']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '09'){
            $db_aset_lancar = $a['yeard']+$a['saldo09d']+$a['saldo08d']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '10'){
            $db_aset_lancar = $a['yeard']+$a['saldo10d']+$a['saldo09d']+$a['saldo08d']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '11'){
            $db_aset_lancar = $a['yeard']+$a['saldo11d']+$a['saldo10d']+$a['saldo09d']+$a['saldo08d']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '12'){
            $db_aset_lancar = $a['yeard']+$a['saldo12d']+$a['saldo11d']+$a['saldo10d']+$a['saldo09d']+$a['saldo08d']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }
        
        if($db_aset_lancar <> '0' && $cr_aset_lancar == '0'){
                $nilaset_lancar = $db_aset_lancar;
                $tot_aset_lancar += $nilaset_lancar;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nilaset_lancar,0));
        }else if($db_aset_lancar == '0' && $cr_aset_lancar <> '0'){
            if($cr_aset_lancar > '0'){
                $nilaset_lancar = $cr_aset_lancar*-1;
                $tot_aset_lancar += $nilaset_lancar;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nilaset_lancar,0));
            }else if($cr_aset_lancar < '0'){
                $nilaset_lancar = $cr_aset_lancar;
                $tot_aset_lancar += $nilaset_lancar;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nilaset_lancar,0));
            }
        }else if($db_aset_lancar <> '0' && $cr_aset_lancar <> '0'){
            $nilaset_lancar = $db_aset_lancar-$cr_aset_lancar;
            $tot_aset_lancar += $nilaset_lancar;
            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nilaset_lancar,0));
        }
    ?>
    </td>
</tr>
<?php 
}
?>
<tr>
    <td style="font-weight:bold;height: 30px;font-size:12px">&nbsp;
        TOTAL ASET LANCAR <!-- Revenue -->
    </td>
    <td align="right"><b>&nbsp;&nbsp; 
    <?php 
    //$tot_aset_lancar
    echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_aset_lancar,0));
    ?></b>
    </td>
</tr>
<tr>
    <td style="font-weight:bold;height: 30px;font-size:14px">&nbsp;
        ASET TIDAK LANCAR <!-- Revenue -->
    </td>
    <td>&nbsp;&nbsp; </td>
</tr>
<?php 
$tot_aset_tidak_lancar;
foreach ($aset_tidak_lancar as $a){
?>
<tr>
    <td>&nbsp; <?php echo $a['nama'];?></td>
    <td align="right">&nbsp;
    <?php 
    
        if($bln == '01'){
            $cr_aset_tidak_lancar = $a['yearc']+$a['saldo01c'];
        }else if($bln == '02'){
            $cr_aset_tidak_lancar = $a['yearc']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '03'){
            $cr_aset_tidak_lancar = $a['yearc']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '04'){
            $cr_aset_tidak_lancar = $a['yearc']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '05'){
            $cr_aset_tidak_lancar = $a['yearc']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '06'){
           $cr_aset_tidak_lancar = $a['yearc']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '07'){
           $cr_aset_tidak_lancar = $a['yearc']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '08'){
            $cr_aset_tidak_lancar = $a['yearc']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '09'){
            $cr_aset_tidak_lancar = $a['yearc']+$a['saldo08c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '10'){
            $cr_aset_tidak_lancar = $a['yearc']+$a['saldo10c']+$a['saldo08c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '11'){
            $cr_aset_tidak_lancar = $a['yearc']+$a['saldo11c']+$a['saldo10c']+$a['saldo08c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '12'){
            $cr_aset_tidak_lancar = $a['yearc']+$a['saldo12c']+$a['saldo11c']+$a['saldo10c']+$a['saldo08c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }
        
        
        
        if($bln == '01'){
            $db_aset_tidak_lancar = $a['yeard']+$a['saldo01d'];
        }else if($bln == '02'){
            $db_aset_tidak_lancar = $a['yeard']+$a['saldo02d']+$a['saldo01'];
        }else if($bln == '03'){
            $db_aset_tidak_lancar = $a['yeard']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '04'){
            $db_aset_tidak_lancar = $a['yeard']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '05'){
            $db_aset_tidak_lancar = $a['yeard']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '06'){
            $db_aset_tidak_lancar = $a['yeard']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '07'){
            $db_aset_tidak_lancar = $a['yeard']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '08'){
            $db_aset_tidak_lancar = $a['yeard']+$a['saldo08d']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '09'){
            $db_aset_tidak_lancar = $a['yeard']+$a['saldo09d']+$a['saldo08d']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '10'){
            $db_aset_tidak_lancar = $a['yeard']+$a['saldo10d']+$a['saldo08d']+$a['saldo08d']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '11'){
            $db_aset_tidak_lancar = $a['yeard']+$a['saldo11d']+$a['saldo10d']+$a['saldo09d']+$a['saldo08d']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '12'){
            $db_aset_tidak_lancar = $a['yeard']+$a['saldo12d']+$a['saldo11d']+$a['saldo10d']+$a['saldo08d']+$a['saldo08d']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }
        
        if($db_aset_tidak_lancar <> '0' && $cr_aset_tidak_lancar == '0'){
                $nilaset_tidak_lancar = $db_aset_tidak_lancar;
                $tot_aset_tidak_lancar +=$nilaset_tidak_lancar; 
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nilaset_tidak_lancar,0));
        }else if($db_aset_tidak_lancar == '0' && $cr_aset_tidak_lancar <> '0'){
            if($cr_aset_tidak_lancar > '0'){
                $nilaset_tidak_lancar = $cr_aset_tidak_lancar*-1;
                $tot_aset_tidak_lancar +=$nilaset_tidak_lancar;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nilaset_tidak_lancar,0));
            }else if($cr_aset_tidak_lancar < '0'){
                $nilaset_tidak_lancar = $cr_aset_tidak_lancar;
                $tot_aset_tidak_lancar +=$nilaset_tidak_lancar;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nilaset_tidak_lancar,0));
            }
        }else if($db_aset_tidak_lancar <> '0' && $cr_aset_tidak_lancar <> '0'){
            $nilaset_tidak_lancar = $db_aset_tidak_lancar-$cr_aset_tidak_lancar;
            $tot_aset_tidak_lancar +=$nilaset_tidak_lancar;
            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($nilaset_tidak_lancar,0));
        }
    ?>
    </td>
</tr>
<?php 
}
?>
<tr>
    <td style="font-weight:bold;height: 30px;font-size:12px">&nbsp;
        TOTAL ASET TIDAK LANCAR <!-- Revenue -->
    </td>
    <td align="right">&nbsp;&nbsp;<b><?php 
    echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_aset_tidak_lancar,0));
    ?></b></td>
</tr>

<tr>
    <td style="font-weight:bold;height: 30px;font-size: 16px">&nbsp;
        TOTAL ASET <!-- Other Expenses -->
    </td>
    <td align="right" style="font-weight:bold;font-size: 16px">&nbsp;&nbsp;<?php 
    echo number_format($tot_aset_lancar+$tot_aset_tidak_lancar,0);?></td>
</tr>


<tr>
    <td style="font-weight:bold;height: 30px;font-size:14px">&nbsp;
        KEWAJIBAN LANCAR<!-- Revenue -->
    </td>
    <td>&nbsp;&nbsp; </td>
</tr>
<?php 
$tot_kw_lancar;
foreach ($balance_kewajiban_lancar as $a){
?>
<tr>
    <td>&nbsp; <?php echo $a['nama'];?></td>
    <td align="right">&nbsp;
    <?php 
    
        if($bln == '01'){
            $cr = $a['yearc']+$a['saldo01c'];
        }else if($bln == '02'){
            $cr = $a['yearc']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '03'){
            $cr = $a['yearc']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '04'){
            $cr = $a['yearc']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '05'){
            $cr = $a['yearc']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '06'){
           $cr = $a['yearc']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '07'){
           $cr = $a['yearc']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '08'){
            $cr = $a['yearc']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '09'){
            $cr = $a['yearc']+$a['saldo09c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '10'){
            $cr = $a['yearc']+$a['saldo10c']+$a['saldo08c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '11'){
            $cr = $a['yearc']+$a['saldo11c']+$a['saldo10c']+$a['saldo09c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '12'){
            $cr = $a['yearc']+$a['saldo12c']+$a['saldo11c']+$a['saldo10c']+$a['saldo08c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }
        
        
        
        if($bln == '01'){
            $db = $a['yeard']+$a['saldo01d'];
        }else if($bln == '02'){
            $db = $a['yeard']+$a['saldo02d']+$a['saldo01'];
        }else if($bln == '03'){
            $db = $a['yeard']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '04'){
            $db = $a['yeard']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '05'){
            $db = $a['yeard']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '06'){
            $db = $a['yeard']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '07'){
            $db = $a['yeard']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '08'){
            $db = $a['yeard']+$a['saldo08d']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '09'){
            $db = $a['yeard']+$a['saldo09d']+$a['saldo08d']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '10'){
            $db = $a['yeard']+$a['saldo10d']+$a['saldo08d']+$a['saldo08d']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '11'){
            $db = $a['yeard']+$a['saldo11d']+$a['saldo10d']+$a['saldo09d']+$a['saldo08d']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '12'){
            $db = $a['yeard']+$a['saldo12d']+$a['saldo11d']+$a['saldo10d']+$a['saldo09d']+$a['saldo08d']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }
        
        
        
        
        if($db == '0' && $cr <> '0'){
            if($cr > '0'){
                $v_kw_lancar = $cr;
                $tot_kw_lancar +=$v_kw_lancar;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($v_kw_lancar,0));
            }else{
                $v_kw_lancar = $cr;
                $tot_kw_lancar +=$v_kw_lancar;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($v_kw_lancar,0));
            }
        }else if($db <> '0' && $cr == '0'){
            if($db > '0'){
                $v_kw_lancar = $db*-1;
                $tot_kw_lancar +=$v_kw_lancar;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($v_kw_lancar,0));
            }else{
                $v_kw_lancar = $db;
                $tot_kw_lancar +=$v_kw_lancar;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($v_kw_lancar,0));
            }
        }else if($db <> '0' && $cr <> '0'){
            $v_kw_lancar = $db-$cr;
            $tot_kw_lancar +=$v_kw_lancar;
            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($v_kw_lancar,0));
        }
    ?>
    </td>
</tr>
<?php 
}
?>
<tr>
    <td style="font-weight:bold;height: 30px;font-size: 12px">&nbsp;
        TOTAL KEWAJIBAN LANCAR <!-- Other Expenses -->
    </td>
    <td align="right" style="font-weight:bold;font-size: 12px">&nbsp;&nbsp;<?php 
    echo number_format($tot_kw_lancar,0);?></td>
</tr>

<tr>
    <td style="font-weight:bold;height: 30px;font-size:14px">&nbsp;
        KEWAJIBAN TIDAK LANCAR<!-- Revenue -->
    </td>
    <td>&nbsp;&nbsp; </td>
</tr>
<?php 
$tot_kw_tidak_lancar;
foreach ($balance_kewajiban_tidak_lancar as $a){
?>
<tr>
    <td>&nbsp; <?php echo $a['nama'];?></td>
    <td align="right">&nbsp;
    <?php 
    
        if($bln == '01'){
            $cr_kw_tidak_lancar = $a['yearc']+$a['saldo01c'];
        }else if($bln == '02'){
            $cr_kw_tidak_lancar = $a['yearc']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '03'){
            $cr_kw_tidak_lancar = $a['yearc']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '04'){
            $cr_kw_tidak_lancar = $a['yearc']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '05'){
            $cr_kw_tidak_lancar = $a['yearc']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '06'){
           $cr_kw_tidak_lancar = $a['yearc']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '07'){
           $cr_kw_tidak_lancar = $a['yearc']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '08'){
            $cr_kw_tidak_lancar = $a['yearc']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '09'){
            $cr_kw_tidak_lancar = $a['yearc']+$a['saldo09c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '10'){
            $cr_kw_tidak_lancar = $a['yearc']+$a['saldo10c']+$a['saldo08c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '11'){
            $cr_kw_tidak_lancar = $a['yearc']+$a['saldo11c']+$a['saldo10c']+$a['saldo08c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '12'){
            $cr_kw_tidak_lancar = $a['yearc']+$a['saldo12c']+$a['saldo11c']+$a['saldo10c']+$a['saldo08c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }
        
        
        
        if($bln == '01'){
            $db_kw_tidak_lancar = $a['yeard']+$a['saldo01d'];
        }else if($bln == '02'){
            $db_kw_tidak_lancar = $a['yeard']+$a['saldo02d']+$a['saldo01'];
        }else if($bln == '03'){
            $db_kw_tidak_lancar = $a['yeard']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '04'){
            $db_kw_tidak_lancar = $a['yeard']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '05'){
            $db_kw_tidak_lancar = $a['yeard']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '06'){
            $db_kw_tidak_lancar = $a['yeard']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '07'){
            $db_kw_tidak_lancar = $a['yeard']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '08'){
            $db_kw_tidak_lancar = $a['yeard']+$a['saldo08d']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '09'){
            $db_kw_tidak_lancar = $a['yeard']+$a['saldo09d']+$a['saldo08d']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '10'){
            $db_kw_tidak_lancar = $a['yeard']+$a['saldo10d']+$a['saldo08d']+$a['saldo08d']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '11'){
            $db_kw_tidak_lancar = $a['yeard']+$a['saldo11d']+$a['saldo10d']+$a['saldo09d']+$a['saldo08d']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '12'){
            $db_kw_tidak_lancar = $a['yeard']+$a['saldo12d']+$a['saldo11d']+$a['saldo10d']+$a['saldo09d']+$a['saldo08d']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }
        
        if($db_kw_tidak_lancar == '0' && $cr_kw_tidak_lancar <> '0'){
            if($cr_kw_tidak_lancar > '0'){
                $v_kw_tidak_lancar = $cr_kw_tidak_lancar;
                $tot_kw_tidak_lancar +=$v_kw_tidak_lancar;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($v_kw_tidak_lancar,0));
            }else{
                $v_kw_tidak_lancar = $cr_kw_tidak_lancar;
                $tot_kw_tidak_lancar +=$v_kw_tidak_lancar;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($v_kw_tidak_lancar,0));
            }
        }else if($db_kw_tidak_lancar <> '0' && $cr_kw_tidak_lancar == '0'){
            if($db_kw_tidak_lancar > '0'){
                $v_kw_tidak_lancar = $db_kw_tidak_lancar*-1;
                $tot_kw_tidak_lancar +=$v_kw_tidak_lancar;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($v_kw_tidak_lancar,0));
            }else{
                $v_kw_tidak_lancar = $db_kw_tidak_lancar;
                $tot_kw_tidak_lancar +=$v_kw_tidak_lancar;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($v_kw_tidak_lancar,0));
            }
        }else if($db_kw_tidak_lancar <> '0' && $cr_kw_tidak_lancar <> '0'){
            $v_kw_tidak_lancar = $db_kw_tidak_lancar-$cr_kw_tidak_lancar;
            $tot_kw_tidak_lancar +=$v_kw_tidak_lancar;
            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($v_kw_tidak_lancar,0));
        }
    ?>
    </td>
</tr>
<?php 
}
?>
<tr>
    <td style="font-weight:bold;height: 30px;font-size: 12px">&nbsp;
        TOTAL KEWAJIBAN TIDAK LANCAR <!-- Other Expenses -->
    </td>
    <td align="right" style="font-weight:bold;font-size: 12px">&nbsp;&nbsp;<?php 
    echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($tot_kw_tidak_lancar,0));?></td>
</tr>


<tr>
    <td style="font-weight:bold;height: 30px;font-size:12px">&nbsp;
        TOTAL KEWAJIBAN<!-- Revenue -->
    </td>
    <td align="right" style="font-size:12px"><b>&nbsp;&nbsp; <?php 
    $totals_kw = $tot_kw_lancar+$tot_kw_tidak_lancar;
    echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($totals_kw,0));?>
        </b>
    </td>
</tr>


<tr>
    <td style="font-weight:bold;height: 30px;font-size:14px">&nbsp;
        EKUITAS<!-- Revenue -->
    </td>
    <td>&nbsp;&nbsp; </td>
</tr>
<?php 
$tot_ekuitas;
foreach ($balance_ekuitas as $a){
?>
<tr>
    <td>&nbsp; <?php echo $a['nama'];?></td>
    <td align="right">&nbsp;
    <?php 
    
        if($bln == '01'){
            $cr_ekuitas = $a['yearc']+$a['saldo01c'];
        }else if($bln == '02'){
            $cr_ekuitas = $a['yearc']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '03'){
            $cr_ekuitas = $a['yearc']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '04'){
            $cr_ekuitas = $a['yearc']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '05'){
            $cr_ekuitas = $a['yearc']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '06'){
           $cr_ekuitas = $a['yearc']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '07'){
           $cr_ekuitas = $a['yearc']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '08'){
            $cr_ekuitas = $a['yearc']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '09'){
            $cr_ekuitas = $a['yearc']+$a['saldo08c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '10'){
            $cr_ekuitas = $a['yearc']+$a['saldo10c']+$a['saldo08c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '11'){
            $cr_ekuitas = $a['yearc']+$a['saldo11c']+$a['saldo10c']+$a['saldo08c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }else if($bln == '12'){
            $cr_ekuitas = $a['yearc']+$a['saldo12c']+$a['saldo11c']+$a['saldo10c']+$a['saldo08c']+$a['saldo08c']+$a['saldo07c']+$a['saldo06c']+$a['saldo05c']+$a['saldo04c']+$a['saldo03c']+$a['saldo02c']+$a['saldo01c'];
        }
        
        
        
        if($bln == '01'){
            $db_ekuitas = $a['yeard']+$a['saldo01d'];
        }else if($bln == '02'){
            $db_ekuitas = $a['yeard']+$a['saldo02d']+$a['saldo01'];
        }else if($bln == '03'){
            $db_ekuitas = $a['yeard']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '04'){
            $db_ekuitas = $a['yeard']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '05'){
            $db_ekuitas = $a['yeard']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '06'){
            $db_ekuitas = $a['yeard']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '07'){
            $db_ekuitas = $a['yeard']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '08'){
            $db_ekuitas = $a['yeard']+$a['saldo08d']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '09'){
            $db_ekuitas = $a['yeard']+$a['saldo08d']+$a['saldo08d']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '10'){
            $db_ekuitas = $a['yeard']+$a['saldo10d']+$a['saldo08d']+$a['saldo08d']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '11'){
            $db_ekuitas = $a['yeard']+$a['saldo11d']+$a['saldo10d']+$a['saldo08d']+$a['saldo08d']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }else if($bln == '12'){
            $db_ekuitas = $a['yeard']+$a['saldo12d']+$a['saldo11d']+$a['saldo10d']+$a['saldo08d']+$a['saldo08d']+$a['saldo07d']+$a['saldo06d']+$a['saldo05d']+$a['saldo04d']+$a['saldo03d']+$a['saldo02d']+$a['saldo01d'];
        }
        
        if($db_ekuitas == '0' && $cr_ekuitas <> '0'){
            if($cr_ekuitas > '0'){
                $v_ekuitas = $cr_ekuitas;
                $tot_ekuitas +=$v_ekuitas;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($v_ekuitas,0));
            }else{
                $v_ekuitas = $cr_ekuitas;
                $tot_ekuitas +=$v_ekuitas;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($v_ekuitas,0));
            }
        }else if($db_ekuitas <> '0' && $cr_ekuitas == '0'){
            if($db_ekuitas > '0'){
                $v_ekuitas = $db_ekuitas*-1;
                $tot_ekuitas +=$v_ekuitas;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($v_ekuitas,0));
            }else{
                $v_ekuitas = $db_ekuitas;
                $tot_ekuitas +=$v_ekuitas;
                echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($v_ekuitas,0));
            }
        }else if($db_ekuitas <> '0' && $cr_ekuitas <> '0'){
            $v_ekuitas = $db_ekuitas-$cr_ekuitas;
            $tot_ekuitas +=$v_ekuitas;
            echo preg_replace('/\-([0-9,.]+)/', '(\1)', number_format($v_ekuitas,0));
        }
        
        
    ?>
    </td>
</tr>
<?php 
}
?>
<tr>
    <td style="font-weight:bold;height: 30px;font-size: 12px">&nbsp;
        TOTAL EKUITAS <!-- Other Expenses -->
    </td>
    <td align="right" style="font-weight:bold;font-size: 12px">&nbsp;&nbsp;<?php 
    echo number_format($tot_ekuitas,0);?></td>
</tr>


<tr>
    <td style="font-weight:bold;height: 30px;font-size: 17px">&nbsp;
        KEWAJIBAN + EQUITAS <!-- Other Expenses -->
    </td>
    <td align="right" style="font-weight:bold;font-size: 16px">&nbsp;&nbsp;<?php 
    $ok = $tot_kw_lancar+$tot_kw_tidak_lancar;
    echo number_format($tot_ekuitas+$ok,0);?></td>
</tr>
</tbody>
</table>

</div>
    